### ISSUE TITLE
Support for MySQL (MariaDB)

### ISSUE THREAD

**Issue by fabiorauber** [Mailu/Mailu#109]
I'm evaluating Mailu to be used as our e-mail solution (great project, by the way), and noticed the database is stored via SQLite in a main.db file. Another e-mail solution I found (docker-compose-mailbox) uses a very light MariaDB image, which I published in https://github.com/interlegis/docker-mariadb-slim. 

What do you think of swapping SQLite for this light MariaDB, or making it configurable? At first, it seems like is not that hard to implement, and brings more flexibility to the combo. In fact, I could work on it and submit a PR.

Best regards.

**Comment by kaiyou** [comment]
This would actually require many changes, including some to Dovecot and Postfix configuration. I agree that we need more flexibility and to make it configurable, but it is unrealistic at this point, actually not as long as we do not have a standard central API for data access by services (see #108 for details on the matter).

Changing the database driver would require that we change Postfix and Dovecot configuration accordingly everytime. We could of course have conditional configuration includes or replacements based on environment variables but that's one hack further that what I can tolerate. I will start working on branch 1.5 pretty soon I believe to make all these possible by the end of the year.

Despite the need for flexibility, what do you think is wrong with SQLite in the current model?

**Comment by wollo** [comment]
For example: I would like to add aliases via a script from a different server. This would be much more straight forward with mysql, as I have already a running central mariadb server wher the docker container with the script has already access to.
With sqlite now I would need to add in teh mailu container some nfs or smb or ssh connection in order to be able to modify the sqlite databse.

**Comment by kaiyou** [comment]
Thank you for the feedback and nice use case that I did not think about.

I see two solutions in the future for your problem:
- using a central database server that both Mailu and your script can access
- having your script access Mailu API

Both will be possible once we have switch to the new API based architecture.

**Comment by fabiorauber** [comment]
While the HTTP API will be really useful, and a better solution for some cases, in the long run a database server will provide more flexibility to the solution, while providing better scalability than SQLite. For instance, what happens when two containers try to write to the database?

**Comment by wollo** [comment]
If you just would mount teh two container inte the same directory, containing teh sqlite database this would be an issue.
So that why I will have to set up some network connectivity between the servers, which will handling file locking. But still there would be theoretically dead locks possibles, while for such things central database software is build.
Nevertheless I must say I like Freeposte/mailu a lot! 

If you like, I can send you some examples form mailcow configuration files, wgich I used before, which is using mysql for postfix and dovecot, if this would be of any help for implementing this.
Of course an api would also be an alternative (2ndd best option in my opinion)

**Comment by kaiyou** [comment]
I believe that we must have both. To maintain compatibility with Postfix and Dovecot while adding features such as 2FA, account lockout, etc. we must have central logic that will handle the details and avoid implementing it in ever-growing SQL statements.

Therefore, the expected architecture is:

- Postfix and Dovecot communicating with central logics (yet to be defined, but a database is not enough for 2FA, IP-based bans, etc. also we must make sure that the services containers we build are as generic as possible)
- Central logic communicating with a database (could be completely agnostic and support whatever SQLAlchemy or Peewee supports)

**Comment by vanthome** [comment]
I want to add that MySQL/ MariaDB and PostgreSQL for example should be much more scaleable for really large setups.
