### ISSUE TITLE
Option project name "-p" is required on startup

### ISSUE THREAD

**Issue by boldt** [Mailu/Mailu#1102]
### Case 1
If I start my containers as follows, everything works fine:

```bash
docker-compose -f docker-compose-mailu.yml -p mailu up -d
```

Log:

```
front_1      | 2019/08/10 19:06:08 [info] 11#11: *4 client 192.168.203.10:37420 connected to 0.0.0.0:10143
front_1      | 127.0.0.1 - - [10/Aug/2019:19:06:08 +0000] "GET /auth/email HTTP/1.0" 200 0 "-" "-"
```

### Case 2

If I ignore the `-p mailu`, I cannot login anymore:

```bash
docker-compose -f docker-compose-mailu.yml up -d
```
Log:

```
front_1      | 2019/08/10 19:03:55 [error] 8#8: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /auth/email HTTP/1.0", upstream: "http://172.18.0.10:80/internal/auth/email", host: "127.0.0.1"
front_1      | 127.0.0.1 - - [10/Aug/2019:19:03:55 +0000] "GET /auth/email HTTP/1.0" 502 166 "-" "-"
```

### Case 2

Changing the name to smth else works as well:

```bash
docker-compose -f docker-compose-mailu.yml -p foobarbaz up -d
```

# Issue

It somehow fails, if I remove the project name parameter. Probably I do not understand, how it influences the start up.

# Expected

It should also work, if I do not use project name.

**Comment by kaiyou** [comment]
If you do not use a project name, the default project name is the name of the current directory.

A project name also defines the network containers run in and the scope of DNS resolution. So if you start all your projects from the same directory and they share a project name, then all your projects are in the same network, which means you are missing the network isolation security bits. Also, DNS is shared, which means all containers will resolve the name of all other containers.

My assumption now, you probably started another compose in that project, which also has a container named admin. Therefore Mailu's front container resolves the wrong IP and tries to connect to your other admin container instead of Mailu's internal API. What happens next is pretty clear from your logs.
