### ISSUE TITLE
Roundcube 1.3 .htaccess overrides PHP upload settings

### ISSUE THREAD

**Issue by jaztec** [Mailu/Mailu#1173]
The [Roundcube 1.3](https://github.com/Mailu/Mailu/blob/master/webmails/roundcube/Dockerfile#L11) release that is used in the Mailu webmail container overrides the work of [`start.py`](https://github.com/Mailu/Mailu/blob/master/webmails/roundcube/start.py#L12) regarding the max upload sizes. 
It would be nice if the Dockerfile could either remove these overrides from the .htaccess or write the calculated values to the .htaccess as well.

See:
https://github.com/roundcube/roundcubemail/blob/release-1.3/.htaccess#L7

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Nebukadneza** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

**Comment by Nebukadneza** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
