### ISSUE TITLE
Antispam gives a 502 Bad Gateway error

### ISSUE THREAD

**Issue by flayks** [Mailu/Mailu#1190]
On mailu 1.7, accessing the `/admin/antispam` gives a 502 Bad Gateway error, since recently I suppose because I was able to go there and check stuff.

The service is up and working tho
```docker
f5e65272d9f2      mailu/rspamd:1.7      "/bin/sh -c /start.py"      2 minutes ago      Up 2 minutes (health: starting)   11332/tcp, 11334-11335/tcp      mailu_antispam_1
```

Logs say that:
```logs
front_1     | 2019/10/03 08:00:26 [error] 8#8: *96 connect() failed (111: Connection refused) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: , request: "GET /admin/antispam/ HTTP/2.0", upstream: "http://192.168.203.7:11334/", host: "mail.domain.com"
```

And I just got this error from the `mailu_antispam_1` container
```logs
antispam_1  | Traceback (most recent call last):
antispam_1  |   File "/usr/lib/python3.7/site-packages/tenacity/__init__.py", line 361, in call
antispam_1  |     result = fn(*args, **kwargs)
antispam_1  |   File "/usr/lib/python3.7/site-packages/socrate/system.py", line 12, in resolve_hostname
antispam_1  |     return socket.gethostbyname(hostname)
antispam_1  | socket.gaierror: [Errno -2] Name does not resolve
antispam_1  |
antispam_1  | The above exception was the direct cause of the following exception:
antispam_1  |
antispam_1  | Traceback (most recent call last):
antispam_1  |   File "/start.py", line 17, in <module>
antispam_1  |     os.environ["ANTIVIRUS_ADDRESS"] = system.resolve_address(os.environ.get("HOST_ANTIVIRUS", "antivirus:3310"))
antispam_1  |   File "/usr/lib/python3.7/site-packages/socrate/system.py", line 20, in resolve_address
antispam_1  |     ip_address = resolve_hostname(hostname)
antispam_1  |   File "/usr/lib/python3.7/site-packages/tenacity/__init__.py", line 292, in wrapped_f
antispam_1  |     return self.call(f, *args, **kw)
antispam_1  |   File "/usr/lib/python3.7/site-packages/tenacity/__init__.py", line 358, in call
antispam_1  |     do = self.iter(retry_state=retry_state)
antispam_1  |   File "/usr/lib/python3.7/site-packages/tenacity/__init__.py", line 332, in iter
antispam_1  |     six.raise_from(retry_exc, fut.exception())
antispam_1  |   File "<string>", line 3, in raise_from
antispam_1  | tenacity.RetryError: RetryError[<Future at 0x7f15b115df98 state=finished raised gaierror>]
```

**Comment by flayks** [comment]
It kind of blocked all my email server to run actually. Couldn't receive any emails!
I switched to the `master` version and reconfigured via the setup and it seems to work again now. Can't tell what it is from tho…

**Comment by kaiyou** [comment]
Will try and reproduce, it looks like clamav is not running, and thus the antispam fails to start.

**Comment by cedricroijakkers** [comment]
I managed to reproduce the issue, it is located within the configuration. I'm running the setup on Kubernetes.

The problem is in the configmap, notably environment variable HOST_ANTISPAM.
This is pointing to "antispam:11332", which is the milter port, which is needed by the postfix container to check for spam on incoming messages.

However, the same environment variable is also used by the nginx container to proxy towards the rspamd http control portal. The problem is that this is not running on port 11332, but on port 11334.

There is a catch-22 here: If you change the variable HOST_ANTISPAM in the configmap file to point to 11334, then the rspamd control panel will start working, but Postfix will reject all mails because it cannot reach the milter.

I have now worked around it by injecting a different environment variable HOST_ANTISPAM in the nginx container than in the postfix container, with port 11334 for nginx and port 11332 for postfix.

The final solution however will probably be adding a new environment variable HOST_ANTISPAM_web pointing to 11334 and use this in nginx, and have postfix use HOST_ANTISPAM (or possibly rename this to HOST_ANTISPAM_MILTER).

**Comment by micw** [comment]
@cedricroijakkers Good finding. I prefer the final solution, created a PR for it.

**Comment by micw** [comment]
Duplicate to #1150

**Comment by KaKi87** [comment]
Hello,

I'm experiencing the same issue just after installing Mailu on Docker while trying to access `/admin/ui` :

```
[error] 7#7: *8 connect() failed (111: Connection refused) while connecting to upstream
```

Are these issues related ?

Thanks.
