### ISSUE TITLE
Better handling of authentication limit

### ISSUE THREAD

**Issue by micw** [Mailu/Mailu#1195]
As discussed in #301 and  #686 the auth limit causes trouble in some scenarios. A probably simple solution would be to only count failed authentications in this limit. To make it still work against brute-force attacks, the behavior should be like:

- If an auth fails, increment the counter
- If the counter is above a certain threshold, reject any auth (valid as well as invalid)
- Don't increment the counter for valid authentication requests

Edit:
- Webmail auth rate limit should be done at HTTP level in nginx so that the limit applies on a per-ip base.

**Comment by micw** [comment]
I created a request for advice at https://github.com/alisaifee/flask-limiter/issues/234

**Comment by micw** [comment]
Related to #634

**Comment by micw** [comment]
I think a custom implementation of https://redislabs.com/redis-best-practices/basic-rate-limiting/ that suits our needs should be quite easily doable

**Comment by dennorske** [comment]
I agree, the approach above was what i initially thought was the case for the service, however I really experienced otherwise when i had the auth limit sat to 10 per minute, and ended up getting logged out from webmail when browsing email. A seperation of the two authentication situations (failure vs successful) would make the limits much easier to adjust.
