### ISSUE TITLE
Disable services

### ISSUE THREAD

**Issue by alu64** [Mailu/Mailu#1242]
I would like to use relayhost to send all the email from mailu server, so I will not need SPF and DKIM to sign outgoing mail. (relay would take care of this).  Do I have to turn it off in mailu?  I also would like to turn off or disable POP3.
What is the proper way to accomplish this? 
I would like to use DMARC.  Is it OK to just use DNS record generated in Domain detalis?

**Comment by kaiyou** [comment]
About pop3, you can disable it per account but not per domain or entirely yet. Some day probably.

Regarding dkim signing (spf is just about the originating ip), you can simply *not* generate keys, then Mailu won't attempt any signature.

Also, you cannot use generated records from the details page because the has to be consistent with the one used by your relay. You should at least change the key in dkim records.
