### ISSUE TITLE
Not able to get going - Invalid letsencrypt

### ISSUE THREAD

**Issue by negativzeroe** [Mailu/Mailu#1243]
Hey all, I've reviewed the documentation and tried to find a forum or telegram group or something but I cannot find any other place for support. I should note that I have the letsencrypt container from linuxserver.io running so I adjusted the port 443 to 4443, the documentation says to remove the front portion of the .yml and add lines to my own config but if I do that it says it needs it when I try to start. I get this error in _front_1:

```
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: mydomain.com
   Type:   unauthorized
   Detail: Invalid response from
   https://mydomain.com/.well-known/acme-challenge/H7F5TQsXusAVya8n3vi1dMKPwLIimrP1ggdXPWFOgLw
   [my.public.ip]: "    <html>\n        <head>\n
   <title>Welcome to our server</title>\n            <style>\n
   body{\n               "

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

But I cannot get to it locally via ip:4443

**Comment by kaiyou** [comment]
The place for support is listed right on top on our landing page and repo, it is the #mailu:tedomum.net Matrix channel.

Also, you basically cannot change the public port and expect Let'sencrypt to run fine. It requires that the service getting the letsencrypt cert listens on the http(s) port.

You can either get a specific IP address for Mailu and listen on that address, then you won't have a port conflict and will be able to use Mailu's own Letsencrypt logic.

Or you can use your existing reverse proxy and Letsencrypt setup. In that case, you should use the `mail` tls flavor, so that Mailu stops listening on port 443 and expecting https input, then point your reverse proxy to the front container. You will also need to extract the letsencrypt certificate and provide it to the front container so that it can accept tls and starttls connections.

Or, as a last resort, you can keep listening on port 4443, setup the `cert` tls flavor and use either a paid certificate or one extracted from your existing letsencrypt.

**Comment by negativzeroe** [comment]
Hi, sorry I must have looked over that. Assuming option one is not viable in my environment, how would I go about modifying the yml for options two or three? Besies TLS_FLAVOR=

**Comment by negativzeroe** [comment]
I'll move to matrix, sorry.

**Comment by kaiyou** [comment]
Here is okay as well if you want to have more developed discussions.
