### ISSUE TITLE
Recipient address rejected: unverified address: Address lookup failure;

### ISSUE THREAD

**Issue by SunMar** [Mailu/Mailu#1292]
Hi,

As mentioned in #38, after upgrading to the latest version recently my catch-all address didn't work anymore, whereas previously it was working fine. The postfix logs showed:

```
Recipient address rejected: unverified address: Address lookup failure;
```

I've been able to resolve it by adding a `postfix.cf` override where I removed `reject_unverified_recipient` from `smtpd_client_restrictions`.

**Comment by SunMar** [comment]
I see the directive was added in this commit: https://github.com/Mailu/Mailu/commit/175349a224c210bceefe918dbe16d66738de8104

**Comment by mindrunner** [comment]
Does this apply to 'latest' only, or also to '1.7' tag?

**Comment by kaiyou** [comment]
It is really interesting that the behavior is only recent. No recent version of postfix seem to change this specifically.

Address verification uses persistent storage however, to avoid spamming remote hosts, and we made some changes there, maybe persisting the queue directory has an impact even if I doubt it.

Anyway, address verification was naively enabled at the time because most docs said it was okay. I have read much documentation against today, especially that it does not help much with anything in general.

I would be quite inclined to disable it altogether, sender and recipient, and see if spam rate actually increases or not.

**Comment by vogelfreiheit** [comment]
Confirming this. Best way to fix this when using a stable tag? How do I store a persistent main.cf override?

**Comment by kaiyou** [comment]
Given the impact, it should be backported to 1.7 once we merge

**Comment by Nebukadneza** [comment]
I don’t quite understand how this breaks catchalls … as they’re also working fine for me currently on `1.7`. On the other hand, I have no strong opinion for/against that check, since i also think most spam is not caught by this, but in later stages (at some computational cost though).
@kaiyou can you oversee this better? If so, from my side, I’d be fine with approve+merge …

**Comment by mathew3** [comment]
I have encountered the same issue (1.7). Interestingly it affected addresses that worked just fine before. Resolved by adjusting `postfix.cf` according to @SunMar 
 
> I've been able to resolve it by adding a `postfix.cf` override where I removed `reject_unverified_recipient` from `smtpd_client_restrictions`.

**Comment by bd8392** [comment]
same issue here

**Comment by Aaron-Ritter** [comment]
Hi, this has as well impact in to relay domains by the looks of it, a server with a configured relay domain has no clue about the final receiving addresses.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by SunMar** [comment]
Hi, the PR I created for this #1293 was actually already merged a while back. Forgot to close this ticket, sorry!
