### ISSUE TITLE
Certwatcher does not work with symlinks (on Kubernetes)

### ISSUE THREAD

**Issue by fionera** [Mailu/Mailu#1302]
I need to recheck this, but I just had this issue... Will report in 3 Months

**Comment by micw** [comment]
I can confirm it, the certs in k8s are renrewed but nginx is not reloaded. I did not restart it yet to have the option to debug it further

**Comment by micw** [comment]
Looks like an issue in certwatcher, dealing with symlinks:

```
bash-5.0# ls -al /certs
total 4
drwxrwxrwt    3 root     root           120 Dec 30 07:21 .
drwxr-xr-x    1 root     root          4096 Nov 30 08:24 ..
drwxr-xr-x    2 root     root            80 Dec 30 07:21 ..2019_12_30_07_21_59.992633671
lrwxrwxrwx    1 root     root            31 Dec 30 07:21 ..data -> ..2019_12_30_07_21_59.992633671
lrwxrwxrwx    1 root     root            15 Nov 30 08:24 cert.pem -> ..data/cert.pem
lrwxrwxrwx    1 root     root            14 Nov 30 08:24 key.pem -> ..data/key.pem
```

**Comment by micw** [comment]
We need to investigate in it, create a test case with symlinks, get it fixed.

**Comment by micw** [comment]
I did some manual tests:

- Direct symlinks works (e.g. cert.pem linked to cert1.pem, then re-linked to cert2.pem triggers the reload/reconfig).
- Indirect symlinks (cert.pem linked to a symlink or symlinked directory which target is changed) are not detected

So the problem here is the way kubernetes changes the symlink.

**Comment by micw** [comment]
@fionera Please re-open it if it still occurs after this fix.
