### ISSUE TITLE
Support ARGON2(I/D) algoritm for password hashing

### ISSUE THREAD

**Issue by EgorRzh** [Mailu/Mailu#1362]
ARGON2(I/D) is prefereable algoritm for hashing password. And  increases popularity. Better to add support of ARGON2 for comfortable import data from another systems.

**Comment by kaiyou** [comment]
Making it the default is a difficult choice, especially due to performance given the amount of password bruteforce on the internet.

However, definitely in favor of adding the option.

**Comment by micw** [comment]
Hardened hash algorithms are a bad choice for non-session based authentication because the password needs to be verified for every single request. So with such a hash (BCrypt or similar) which is designed to run slow and/or to consume lots of resources a single webmail user can saturate all resources of a server.
(example: https://www.endpoint.com/blog/2016/02/09/bonked-by-basicauth-because-bcrypt)

It's the same for all hashes of this type. Using apr1 or similar is the best choice here.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Nebukadneza** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

**Comment by nextgens** [comment]
We now support importing argon hashes in master... they'll be converted on first use to what is current (bcrypt+sha256)
