### ISSUE TITLE
extern Nginx Routing / Docker Compose

### ISSUE THREAD

**Issue by pherting** [Mailu/Mailu#1374]
Hello,
iam using a Debian VPS with local Nginx installed.
I want to use Mailu with Docker, i changed the docker-compose.yml
with ports: 8080:80 and 8443:443.
Also i added in my local nginx default config:
location /admin {
    		proxy_pass https://localhost:8443/admin;
  	}
For Admin and same for webmail.
But i dont get the Site, only error bad connection refused..
In the Docu at mailu.io/master/reverse.html thats exact the same way.. i dont now whats missing.

maybee some one can help me :/
Thanks a lot!

**Comment by a575606** [comment]
I am in the same boat, but using a dockerized nginx / letsencrypt reverse proxy setup. I am trying to merge mailu's docker compose into my existing compose, which includes an nginx reverse proxy, wordpress, mariadb and phpmyadmin containers. 

I've tried following the instructions in the docs, similar to @pherting and have tried many different approaches in addition, and none seem to work. It seems no matter which way I try to connect, there is some sort of 502 or connection refused error, including even curl from within my web proxy container to the 'front' mailu container. what could be causing the blocks?

Also is there any way to run mailu using a different UID and GID? I'm concerned this may be a permissions issue.

**Comment by vjaro** [comment]
@pherting i encountered the same with you and after reading through the documentation you can do the following:

1. Change the port mapping on the docker-compose which you have been doing now.
2. Use `notls` if your installation is for local testing only.
3. If you want to use TLS, in my case i used `mail` and generate self signed certificates. You have to modify the docker-compose.yml file like this:

> front:
volumes:
      - "../certs:/certs"
      - "/mailu/overrides/nginx:/overrides"

on your /mailu directory, create a /certs folder and create the key.pem and cert.pem certificates under that folder.

For local testing only i think step 1 and 2 would suffice.
I'm not an expert but it these things helped me.

**Comment by vjaro** [comment]
@a575606 i'm not an expert however i'm in the same situation as you are.
So in my scenario i have an app with a separate docker-compose.yml file and this mailu docker installation.
Initially these two apps, will be on a different docker network so either you move the mailu to your wordpress network.

In my case, i retained the docker-compose.yml configuration for my other web app, and modified the docker-compose.yml file for the mailu installation.
Instead of using the default network for the mailu app, i've just added the mailu app to the existing web app's network:

Mailu docker-compose.yml file
> networks:
  default:
    external:
      name: web_app_network

These will merge the two apps in the same network. One thing you need to be aware of is the port conflicts. You need to update the ports for the services that are the same.

Hope this helps.

**Comment by a575606** [comment]
Hi @vjaro , thanks for the tip. Yes, I managed to get my install working using a similar solution. Using the same network as my nginx proxy allowed me to refer to the 'front' container by name, which seemed to make everything happy. My modified nginx config in my nginx reverse proxy looked like this if that helps anyone:

```
location /mailadmin {
    return 301 $scheme://$host/mailadmin/;
}
location ^~ /mailadmin/ {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_front front;
    proxy_pass https://$upstream_front;
}
```

**Comment by mathew3** [comment]
@pherting I have done following

1. Clean install mailu, make sure webmail and admin are working correctly
2. Set up nginx on you server, I used [this tool](https://www.digitalocean.com/community/tools/nginx#) to generate the config
3. Change ports in mailu's `docker-compose.yml` according to the [docs](https://mailu.io/master/reverse.html#have-mailu-web-frontend-listen-locally)
4. Adjust server's (not mailu's) nginx config

`/etc/nginx/sites-enabled/yourdomain.tld.conf`

```
server {
        # stuff...

        root /path/to/frontend/folder;

        # stuff...

	location ~ ^/admin/? {
		proxy_pass https://127.0.0.1:8443;
		include nginxconfig.io/proxy.conf;
	}

	location ~ ^/webmail/? {
		proxy_pass https://127.0.0.1:8443;
		include nginxconfig.io/proxy.conf;
	}

        location /api {
		proxy_pass http://127.0.0.1:3334;
		include nginxconfig.io/proxy.conf;
	}

        # stuff...
}
```

As you can see, I have my API running on port 3334. Hope this helps

**Comment by vinanrra** [comment]
@mathew3 @a575606 can u guys help me with this problem? https://github.com/Mailu/Mailu/issues/1459

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by vinanrra** [comment]
Check this i had a similar problem too:

#1459

**Comment by Nebukadneza** [comment]
This seems to be a user-setup question. Currently, we much prefer to have user-setup questions in the matrix channel (https://matrix.to/#/#mailu:tedomum.net). Please head over there for support. 


We also see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
