### ISSUE TITLE
Outgoing traffic blocked on port 25

### ISSUE THREAD

**Issue by masterobiwan** [Mailu/Mailu#1455]
Hi there,
I have deployed mailu on AWS EC2 instance. Everything seems to work well except I cannot send a single email to the outside world (tested using roundcude webmail). Receiving emails works fine. I had a look to smtp service logs when trying to send an email to gmail address and the problem seems to be:

> smtp_1       | Apr 17 21:43:38 mail postfix/smtp[5075]: connect to gmail-smtp-in.l.google.com[74.125.193.26]:25: Operation timed out

On the mailu server I tried:
`telnet gmail-smtp-in.l.google.com 25`
and got
> Trying 74.125.193.26...
Trying 2a00:1450:400b:c01::1a...
telnet: Unable to connect to remote host: Network is unreachable

However when I do from another server:
`telnet my.mailu.server.com 25`
I can establish the connection.

I am definitely no network nor docker expert, so maybe my docker compose config is not correct, so I include the parts that may be relevant to me:
>  Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "10.0.0.90:80:80"
      - "::1:80:80"
      - "10.0.0.90:443:443"
      - "::1:443:443"
      - "10.0.0.90:25:25"
      - "::1:25:25"
      - "10.0.0.90:465:465"
      - "::1:465:465"
      - "10.0.0.90:587:587"
      - "::1:587:587"
      - "10.0.0.90:110:110"
      - "::1:110:110"
      - "10.0.0.90:995:995"
      - "::1:995:995"
      - "10.0.0.90:143:143"
      - "::1:143:143"
      - "10.0.0.90:993:993"
      - "::1:993:993"
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides"
  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/overrides:/overrides"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24

Do you have any idea where the problem could come from?
Thanks a lot.

**Comment by AndrewSav** [comment]
Without more evidence, it sounds to that it's more likely that the problem is on on the AWS side rather than maily side. I suggest you do connectivity tests on the EC2 instance first and from the smtp container second. If you discover that you cannot connect from EC2 instance itself you will need to seek help with your AWS setup.

**Comment by AndrewSav** [comment]
>On the mailu server I tried:
>`telnet gmail-smtp-in.l.google.com 25`

Since you cannot connect from EC2 instance to google smtp this is not a mailu problem, and you should seek AWS help. This is unlikely to be a problem with mailu. If telnet cannot connect, mailu certainly cannot connect either.

Since you are trying that from the host, it is also not likely to have anything to do with docker.

**Comment by masterobiwan** [comment]
Hi Andrew. Thanks for your feedback. I have asked to AWS to remove the email sending limitation. I hope this will solve the issue, but I am not sure since from what I read on forums, users impacted by this limitation could send few emails before facing the limitation, which is not my case since I can't send a single one. If this does not solve the issue, I'll create a case on AWS support.

**Comment by capslocky** [comment]
I have also stumbled over this. It turns out all major cloud providers by default block outgoing connections to port 25: [Azure](https://docs.microsoft.com/en-us/azure/virtual-network/troubleshoot-outbound-smtp-connectivity), [AWS](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/), [GCP](https://cloud.google.com/compute/docs/tutorials/sending-mail). My workaround was setting up external smtp relay with custom port:
```
RELAYHOST=smtp.sendgrid.net:587
RELAYUSER=apikey
RELAYPASSWORD=...
```
I don't like this kind of dependency on external service. And the free plan offered by SendGrid is limited to 100 letters per day. But my free cloud plan on Azure doesn't allow me to request lifting of this restriction.

**Comment by masterobiwan** [comment]
Thanks for the feedback. The limitation removal process is still ongoing with AWS. They are asking me more details on my use case, the measures inplace to avoid that unwanted email is sent from the server and reverse DNS records. I'll go further and keep you informed of the outcome.

**Comment by masterobiwan** [comment]
AWS finally proceeded with the limitation removal and now I can send email from mailu server. It still doesn't work sending to gmail, maybe my emails are classified as spam. I am also working with AWS so they configure reverse DNS for my email domain name. For that purpose they ask that there is a PTR record matching the existing A record. So I just added a PTR record in my DNS records. Let see if it works like that. Anyways the issue is not with mailu. Thanks for your support!
