### ISSUE TITLE
 554 5.7.1 Sender address rejected: Access denied while sending from another server

### ISSUE THREAD

**Issue by anthonyaaa** [Mailu/Mailu#1456]
Hi guys,

Thank you for the mailu.io initiative! :slightly_smiling_face: I'm currently testing it but I'm stuck on one issue.

I'm sending emails from a web server hosted on a separate machine. If I send these emails using for both at the same time the _to:_ and _from:_ fields an email address managed by mailu, I get a _554 5.7.1 Sender address rejected: Access denied_

E.g.: mailu manages emails for domain.com : I use my web server (different from the mailu server) to send emails using contact@domain.com to john.doe@domain.com -> the email is rejected.

Any idea how I can fix it?

Many thanks,
Anthony

**Comment by anthonyaaa** [comment]
Hi,

If someone is reading this, I haven't found the solution yet but I'm using a workaround. I'm using the contact@domain.com account through SMTP. At first by relaying from the web server and now using the account with a token.

**Comment by ofthesun9** [comment]
I think you found the proper solution indeed ;-)
The alternative is to use the RELAYNETS env variable so that your webserver will be allowed to use Mailu as a relay. Be careful with this approach as you can create inadvertently an open relay..
IMHO, your approach is as good, if not better -:)
Therefore closing the issue, but feel free to reopen if needed.
