### ISSUE TITLE
PROXY Protocol support

### ISSUE THREAD

**Issue by unixfox** [Mailu/Mailu#1472]
Hello,

I'm trying to deploy Mailu behind a load balancer but it seems that Mailu doesn't support the PROXY Protocol.

Would it be feasible to add support for the PROXY Protocol?
From I can see the NGINX documentation allows switching to the PROXY Protocol: https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/ but I don't know if this can easily be implemented into Mailu.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
We are currently not planning to add such functionality. There are simply to many other more pressing items on the backlog.
You are free to create a PR for this. We will be happy to review it and include it to Mailu.

**Comment by snotrman** [comment]
Hello! I've been at this issue for days. Could you please help?

![image](https://user-images.githubusercontent.com/37236334/95546759-1698de80-0a0a-11eb-8426-482c152fa3b7.png)
- /admin and /webmail both load without css

![image](https://user-images.githubusercontent.com/37236334/95546845-447e2300-0a0a-11eb-9c78-d935fbc94512.png)
- I see that the /admin location is able to take arguments for its paths from as I can type /admin and I will be redirected to admin/ui/login?next=ui.index

![image](https://user-images.githubusercontent.com/37236334/95559583-ab0e3b80-0a20-11eb-9940-9d0eb7f89be3.png)
- I am able to log in judging from logs. But there is no change in the UI, because I presume it is handled my javascript, which is not loading

![image](https://user-images.githubusercontent.com/37236334/95556910-b5c6d180-0a1c-11eb-8637-77b6686c0c8b.png)
![image](https://user-images.githubusercontent.com/37236334/95558220-90d35e00-0a1e-11eb-8444-8708dcfd638c.png)
- These are my containers and forwarded ports


![image](https://user-images.githubusercontent.com/37236334/95558421-e0198e80-0a1e-11eb-9506-05329b1c04dd.png)
![image](https://user-images.githubusercontent.com/37236334/95558464-f0ca0480-0a1e-11eb-8583-dd683a7a7024.png)
![image](https://user-images.githubusercontent.com/37236334/95558517-017a7a80-0a1f-11eb-8191-b3b1ac111fc7.png)
![image](https://user-images.githubusercontent.com/37236334/95558560-18b96800-0a1f-11eb-9d95-f136a75bdaaf.png)
- My relevant nginx config

- And also I have 2 node servers listening on 
  http://95.179.178.116:6080
  http://anotherdomain.lv:8085



- This happened all of a sudden when I routinely checked if /webmail is working.

- I see that incomming mail is being received, but users have been deleted!!! This wasn't so important now, because I just created the email a couple of days ago. But it would have been a disaster for a large production  setup. I don't know why this is happening and what happened to the deleted users and their mail.
 
![image](https://user-images.githubusercontent.com/37236334/95560695-4eac1b80-0a22-11eb-9bc5-5a2d579b1096.png)
- These are all the commands regarding mailu I've done

Please advise 
Thank you 

#1528

**Comment by snotrman** [comment]
Hey! For somebody running into this -- check your mail.yourdomain.com/webmail. It should work. And you are safe to issue a new certificate for mail.yourdomain.com also.

And to make the /admin run on mail.yourdomain.com you need to set header as so:

    location / {
        proxy_pass https://localhost:8443;
        proxy_set_header Host $http_host;
    }

**Comment by snotrman** [comment]
I solved the issue it was the

![image](https://user-images.githubusercontent.com/37236334/95583258-8330cf00-0a44-11eb-8eb3-2c9f8a556daf.png)

This made all .js .css files not redirect.

**Comment by unixfox** [comment]
@snotrman how is that related to the PROXY protocol?

**Comment by Diman0** [comment]
Mailu 2.0 supports the proxy protocol. Closing issue.
