### ISSUE TITLE
Usable as a « mailtrap » ?

### ISSUE THREAD

**Issue by rroblik** [Mailu/Mailu#1508]
Dear

I’ve spend lot of time reading the pretty clear documentation. Before trying to implement this awesome work I want to be sure that it catch my needs, can you help me to be sure of that ?

Needs a docker (swarm) stack that can be used to works as a fake smtp relay for multiple other stacks (application) in the cluster. Final goal is to : 
* prevent spamming real users while allowing sending email like with a real smtp server (with auth) 
* allowing users to see sent emails Using web interface 

For now I’m using a little bit outdated Mailhog on each stack but maybe this tool can help me to centralize things in one place. 

Thanks for your answer

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
I'm not sure what you want. You want Mailu to pretent it sends authenticated mail and then drop the email instead of sending it? 
Is that what you mean with
- fake smtp relay for multiple other stacks (application) in the cluster. 
This might be possible by configuring a non existing smart host (RELAYHOST in mailu.env). See RELAYHOST in the [configureation reference] (https://mailu.io/1.7/configuration.html). With a non-existing smart host Mailu will try to relay all outgoing email via this non-existing mail server and will eventually give up. You could for example configure localhost with a non used port.

- allowing users to see sent emails Using web interface
Mailu comes with either Roundcube or Rainloop which you can use to see send emails. This only works if the email client for sending the email saves a copy in the sent folder. Mailu does **not** copy an email to the sent folder when sending emails.
