### ISSUE TITLE
No elastic theme in roundcube webmail

### ISSUE THREAD

**Issue by drew6017** [Mailu/Mailu#1520]
Using Mailu 1.7 there is no elastic theme available for the Roundcube webmail client.

Apparently Mailu 1.7 is still using Roundcube 1.3.10 which is quite old and unable to support the theme. https://test.mailu.io/ is using the elastic theme so I am assuming it is running from the master branch.

When are you planning on finalizing a release with a version of Roundcube that has the elastic theme?

**Comment by Nebukadneza** [comment]
1.8 is on the way since a while, and most of the team agree that a release is actually overdue. In the past few weeks-to-months most of us have been quite busy though — but rest ensured it’s on our minds at least :(

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by lub** [comment]
For progress on the 1.8 release you can btw now have a look at https://github.com/Mailu/Mailu/milestone/10 and https://github.com/Mailu/Mailu/milestone/11

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

p.s. to answer your question, we are almost finished with all tasks left for developing 1.8. Hopefully we will have a release candidate ready in October and will be able to release in November/December. This all depends on the availability of the volunteers in the project.
