### ISSUE TITLE
Enable RainLoop Admin UI 

### ISSUE THREAD

**Issue by kmoens** [Mailu/Mailu#156]
Currently the rainloop admin ui is disabled. Still I would like to use it for my installation of Mailu.

Can I override this right now?
If not, I could see to create a pull request which enables the webui as an option.

**Comment by trueserve** [comment]
You can override it (and other Rainloop settings) manually be editing the config in your mailu-top-dir/webmail/_data_/_default_/configs directory. They may not persist through updates though (didn't for me), so keep backups.

**Comment by kmoens** [comment]
That's what I do now, but this doesn't even seem to surive a restart of the container, unless I'm doing something wrong :).

**Comment by kaiyou** [comment]
Currently the configuration is overwritten at startup. I disabled the WebUI mostly because some options will break the Webmail. It would probably be best to have a override folder for Rainloop configuration where you could either add settings directly or enable the WebUI.

When enabling the WebUI however, I have no idea how configuration should be made persistent.

**Comment by kaiyou** [comment]
The current philosophy is to not enable third party admin ui and keep things simple. Closing.
