### ISSUE TITLE
User Settings: Spam filter threshold does not influence the behaviour of rspamd

### ISSUE THREAD

**Issue by jukey** [Mailu/Mailu#158]
Whenever I change the value of the Spam filter threshold in the 'User Settings' dialog It seems to be stored (as I get the changed value when I go to the page later again) but the behaviour of rspamd does not change. The threshold there still keeps to be 15, which is the default value.

To be more concrete:
- I changed the Threshold in the webinterface of the mailu user settings from 80 to 5.
- All emails keep the following header (exapmle): `X-Spamd-Result: default: False [-0.10 / 15.00]`

How to investigate this issue further?

**Comment by kaiyou** [comment]
This is actually the expected behaviour. To avoid having configuration issues with various antispam systems once we support multiple of them, we decided not to change the antispam settings but the response behaviour.

In the Dovecot configuration, the sive script that manages spam takes care of actually dropping messages. It first computes a percentage from the score then compares it with the configured value, per user.

**Comment by jukey** [comment]
Thanks for the explanation.

The described mechanism makes it hard for mail users to understand their spam setting made in the mailu configuration web interface and the results. It could be useful to add the mailu score to an additional header.

**Comment by kaiyou** [comment]
That's a great idea actually. I'll see if it is possible in sieve.

**Comment by fabiorauber** [comment]
I was actually trying to understand how it works... Having a header would help a lot. =)

**Comment by kaiyou** [comment]
It seems possible using sieve. Feel free to pull request, otherwise I will work on it in the next couple of weeks given the priority.

**Comment by nils-wisiol** [comment]
I am having a lot of spam coming through with `X-Spamd-Result: default: False [9.70 / 15.00]` but `X-Spam: yes`. 

Would this issue change that behavior?
How can mail with `X-Spam: yes` get through in the first place?

My threshold is currently set to 60%, i.e. 9.75/15.

Also, @kaiyou, thats for your awesome work here.

**Comment by kaiyou** [comment]
Thank you for providing feedback, this is merely the work I do for myself and care to share because.. hell, someone could enjoy using it :)

Regarding the spam thresholds and the `X-Spam` header, they are managed separately and the result can indeed be counter-intuitive. The header is place by `rspamd` that has its own default global threshold, which is ignored by Mailu because we need per-user thresholds. Then, upon delivery, Dovecot (Pigeonhole specifically) parses the score and compares it to the threshold before actually making a decision.

So indeed, the final decision, which depends on your threshold, may contradict the `rspamd` header, which depends on a global default threshold.

**Comment by mabunixda** [comment]
My threshold was on 80 and i get mails with `X-Spamd-Result: default: False [9.75 / 15.00]` into my inbox instead into Junk folder :-( I raised it now to 90 and still get mails with even 8.85 delivered ....

**Comment by kaiyou** [comment]
Again, this might not be the most obvious and maybe we need to specify a more meaningful setting, but he spam setting is a percentage. So 80 means 80% of 15, which is 12. Also, the `True` or `False` flag is related to rspamd threshold, which is 10 by default and not used in Mailu.

Finally, rspamd and most antispam software use a negative scoring for spam. The higher the score, the higher the probability the message is junk. So 8.85 being less than 12 is still less than 80% :)

**Comment by mabunixda** [comment]
@kaiyou so you must lower the rate to get a higher spam matching? i thought the higher the rating less spam i will receive and not more ...

**Comment by kaiyou** [comment]
The "rating" is a threshold. When an email gets a score above that threshold, it is classified as spam. So the lower the threshold, the less tolerant the system is to spam. Maybe we could rename the threshold "spam tolerance".

**Comment by kaiyou** [comment]
I renamed the field in ``master``, also the header changed due to migrating to rspamd.
