### ISSUE TITLE
freshclam log is not on stdout

### ISSUE THREAD

**Issue by lub** [Mailu/Mailu#1632]
`freshclam` is started with `-d` and thus forks into the background. That way there are no log messages regarding successful/failed/skipped updates.

In bash it would probably be something like this

```sh
freshclam -c 6 &
clamav
```

**Comment by ghostwheel42** [comment]
I opt for:
- remove/disable syslog in freshclam.conf
- change PidFile to /run/freshclam.pid in freshclam.conf
- add --stdout to start command

**Comment by botihu** [comment]
I have found something with my more deep tests: running `freshclam` in the foreground is not an option, given it is just a onetime update. 

According to https://docs.clamav.net/faq/faq-safebrowsing.html the update of the SafeBrowsing data file has been stopped by ClamAV project (doe to changes in Google's licensing). This stanza also can be removed from the freshclam.conf. 

If we would add `UpdateLogFile /dev/stdout` to the freshclam.conf and would change the pid file file would be also sufficient. In this case the first time update command also need patched to `os.system("freshclam --quiet")` in order to avoid doubled lines sent to stdout at the time of first DB download.

**Comment by ghostwheel42** [comment]
@botihu I've submitted a proposed fix
