### ISSUE TITLE
Setup in cluster or hi availability scenario?

### ISSUE THREAD

**Issue by lucianlazar1983** [Mailu/Mailu#1637]
Hi there, is it possible in the current state to create a hi availability mailu system? For example have multiple containers for each role (dovecot, postfix, and so on) in order to have them handle with failover or to have instances in multiple regions with the same ingres. Thank you!

**Comment by lub** [comment]
Currently it's not possible for all components. It's de facto not possible to reliably run multiple Postfix and Dovecot by just pointing them to a shared storage, because this results in problems problems regarding the mail queue and access to mailbox filesystems.

https://github.com/Mailu/Mailu/tree/master/docs/swarm/master#when-disaster-strikes describes some of these issues and there is some discussion about it in #1224 and #1222 regarding possible solutions.

Right now you can of course already use something like swarm to re-schedule containers as soon as they crash/a host gets unavailable/.., but if this is enough is up to you :)
