### ISSUE TITLE
High CPU spikes and lot of RAM used

### ISSUE THREAD

**Issue by askz** [Mailu/Mailu#166]
Hi, my Mailu instance had been a little buggy theses last days, I monitor with Zabbix and got often imap/pop service down for no reason.
And yesterday, when lot of down/up messages appeared I found that rspamd was using 100% of the cpu
and clamd using a lot of ram (~46%) and 36% at the time I'm writing.
Here's is the CPU when rspamd was spiky and I restarted the whole thing.: 
![mailu-cpu](https://cloud.githubusercontent.com/assets/854038/23171417/b5b52fdc-f852-11e6-982c-7576e67b626b.png)

Here's the ram : 
![mailu-ram](https://cloud.githubusercontent.com/assets/854038/23171422/bb01ff2e-f852-11e6-9a28-907c4eb143c9.png)

My instance is a cheap vps at scaleway with 2vCores 2GB of RAM and 50GB SSD.

Did someone got that kind of issue recently ?
I never had issues like that for 6months I've been running it, we have 3 domains and like 10 mailboxes

**Comment by kaiyou** [comment]
Clamd using lots of ram is definitely not new. As soon as virus databases are loaded, you should expect clamd to use 1GB of memory, and there is not much we can do about it except loading virus databases on the fly, which will require awful IO everytime a mail is received.

The CPU spikes and flaps are more alarming though. I have not seen anything like it for now. Could you have a look at the imap container logs, searching for error messages and unreasonable amounts of connections?

What could explain part of the problem is if you recreate the container everytime it fails instead of restarting it, as IMAP will create new DH parameters everytime, using lots of CPU, especially on a VPS where entropy is expansive.

**Comment by askz** [comment]
Hi @kaiyou.
It's the third time now I can observe this phenomenon. I think it's not the Mailu fault but attackers. 
I can see a lot of requests attempts on smtp in fact. 
I'll update this soon when I'll gather more details

**Comment by askz** [comment]
Closing this since it was sucession of attacks (DoS)

Thanks.
