### ISSUE TITLE
is there some kind of IP address blocking ?

### ISSUE THREAD

**Issue by gilasraafi421** [Mailu/Mailu#1664]
Environment
 - docker-compose

Versions
 - 1.7

Description
hello guys, i want to ask any questions or suggestions for how to block ip address on authentication because when i look at the front log it seems that someone is Brute-force the authentication. I've tried blocking on UFW, but it doesn't work. Thank you.

![Image of Front Log](https://i.ibb.co/r6NvX2t/Screen-Shot-2020-10-17-at-19-43-17.png)

**Comment by lub** [comment]
Mailu has built-in rate limiting of by default 10/minute and 1000/hour. You can also modify this via AUTH_RATELIMIT.

Besides that you can also block the address in your own firewall/iptables/.., but in case of iptables you have to watch out to place the rules in the correct chains because docker itself also utilizes iptables by default to enable access to the exposed services. See for example https://github.com/chaifeng/ufw-docker#solving-ufw-and-docker-issues (untested; I have never used ufw myself).

But it doesn't matter on port 25 anyway, because Mailu doesn't allow authentication on port 25. https://mailu.io/master/faq.html?#a-user-gets-sender-address-rejected-access-denied-please-check-the-message-recipient-and-try-again-even-though-the-sender-is-legitimate
