### ISSUE TITLE
Mail not delievered when using PGP Encryption Keys and Sieve transfers

### ISSUE THREAD

**Issue by falcosmash** [Mailu/Mailu#1698]
Hi everyone,

I recently updated Mailu to version 1.8 and PGP encryption keys + Sieve transfers (Copy received mail to another mailbox) the mail are stuck in queue.
If I disable the copy to another I receive all the previous mail that has been sent to me encrypted. I do not have the problem if the message are sent to me unencrypted 

### Environment
 - docker-compose
```

### Versions
All the mailu containers are running V1.8
```

## Expected behaviour
For me the mails should be sent copied encrypted to the other mailbox.
```

## Logs

```
$ docker-compose logs --follow --tail 100 | grep smtp
...
smtp_1       | Nov 26 12:15:14 elektr postfix/smtpd[96602]: connect from mailu_front_1.mailu_default[192.168.203.3]
smtp_1       | Nov 26 12:15:14 elektr postfix/smtpd[96602]: 3A856BE7006E: client=mailu_webmail_1.mailu_default[192.168.203.11], sasl_method=XCLIENT, sasl_username=alice@example.org
smtp_1       | Nov 26 12:15:14 elektr postfix/cleanup[96605]: 3A856BE7006E: replace: header Received: from localhost (mailu_webmail_1.mailu_default [192.168.203.11])??by example.org (Postfix) with ESMTPA id 3A856BE7006E??for <bob@example.org>; Thu, 26 Nov 2020 12:15:14 +0000 (UTC) from mailu_webmail_1.mailu_default[192.168.203.11]; from=<alice@example.org> to=<bob@example.org> proto=ESMTP helo=<localhost>: Received: from authenticated-user (PRIMARY_HOSTNAME [PUBLIC_IP])??by example.org (Postfix) with ESMTPA id 3A856BE7006E??for <bob@example.org>; Thu, 26 Nov 2020 12:15:14 +0000 (UTC)
smtp_1       | Nov 26 12:15:14 elektr postfix/cleanup[96605]: 3A856BE7006E: message-id=<a3d17c9e67733875e000e20d8e2ea942@example.org>
smtp_1       | Nov 26 12:15:14 elektr postfix/qmgr[388]: 3A856BE7006E: from=<alice@example.org>, size=7221, nrcpt=1 (queue active)
smtp_1       | Nov 26 12:15:14 elektr postfix/smtpd[96602]: disconnect from mailu_webmail_1.mailu_default[192.168.203.11] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=1 quit=1 commands=6/7
imap_1       | Nov 26 12:15:14 lmtp(bob@example.org)<112844><9Mw1E1Kcv1/MuAEAEIr4Hw>: Error: smtp-client: conn 192.168.203.3:25 [1]: read((conn:192.168.203.3:25,id=1)) failed: read(size=8010) failed: Connection reset by peer
imap_1       | Nov 26 12:15:14 lmtp(bob@example.org)<112844><9Mw1E1Kcv1/MuAEAEIr4Hw>: Error: sieve: msgid=<a3d17c9e67733875e000e20d8e2ea942@example.org>: redirect action: failed to redirect message to <bob@protonmail.com>: smtp(192.168.203.3): RCPT TO failed: Lost connection to remote server (read failure) (temporary failure)
smtp_1       | Nov 26 12:15:14 elektr postfix/lmtp[96606]: 3A856BE7006E: to=<bob@example.org>, relay=192.168.203.10[192.168.203.10]:2525, delay=0.13, delays=0.07/0.02/0.01/0.02, dsn=4.2.0, status=deferred (host 192.168.203.10[192.168.203.10] said: 451 4.2.0 <bob@example.org> Execution of Sieve filters was aborted due to temporary failure (in reply to end of DATA command))
````

**Comment by tremlin** [comment]
I've been seeing the same issue for mails in a similar scenario (e-mails sent to an address which has a `redirect :copy` rule in sieve).
This weekend I have debugged this issue as much as I could and I think the problem is the following:
1. dovecot/sieve tries to send the email and opens a connection to the frontend (nginx) server to submit the e-mail
2. dovecot uses SMTP pipelining and chunking to do so.
3. In the response from the frontend (nginx) server to dovecot only the last command (bdat), not the mail/rcpt commands are acknowledged:
```
S: 220 mail.xxx ESMTP ready
C: EHLO mail.xxx
S: 250-mail.xxx
S: 250-PIPELINING
S: 250-SIZE
S: 250-50000000
S: 250-ETRN
S: 250-ENHANCEDSTATUSCODES
S: 250-8BITMIME
S: 250-DSN
S: 250-CHUNKING
S: 250 STARTTLS
C: MAIL FROM:<yyy>
C: RCPT TO:<zzz>
C: BDAT 4904 LAST
C: [4904 bytes]
S: 250 2.0.0 OK
[S closes connection]
```
This seems to throw off dovecot and it reports a temporary failure.
I am not a protocol expert so I don't know if this just a symptom of another problem or which part is to blame.

As a temporary solution for our installation I patched the frontend/nginx server so that it does not announce SMTP pipelining any more. Then the communication between dovecot and frontend/nginx is being performed without pipelining and everything works well.

**Comment by fracture-point** [comment]
I am also experiencing an issue with what appears to be the same root cause.  I have a sieve rule, configured via Rainloop, which forwards an incoming email to an external server.  The forward fails, with this error:

```
imap_1        | Apr 02 23:58:29 lmtp(MASKED@MASKED.com)<7400><MASKED>: Error: sieve: msgid=<MASKED@MASKED.com>: redirect action: failed to redirect message to <MASKED@MASKED.net>: smtp(192.168.203.5): RCPT TO failed: Lost connection to remote server: Read failure (temporary failure)
```

In my case, I can't get a sieve rule to forward an email externally. Has anyone figured out a solution to this?
