### ISSUE TITLE
podop raise exception on `username@[ip]` address 

### ISSUE THREAD

**Issue by jeanlucmongrain** [Mailu/Mailu#1750]
Using 1.8 master docker images in kubernetes.

Testing if it's an openrelay with http://www.aupads.org/test-relay.html and whenever the address is in format `username@[ip]` it raise exception:

```
Feb 03 10:25:36 mail postfix/smtpd[281512]: warning: socketmap:unix:/tmp/podop.socket:senderaccess socketmap server temporary error: unknown error
Feb 03 10:25:36 mail postfix/smtpd[281512]: warning: socketmap:unix:/tmp/podop.socket:senderaccess lookup error for "spamtest@[x.y.z.w]"
Feb 03 10:25:36 mail postfix/smtpd[281512]: NOQUEUE: reject: RCPT from santuario.pads.ufrj.br[146.164.48.5]: 451 4.3.5 <spamtest@[206.189.154.202]>: Sender address rejected: Server configuration error; from=<spamtest@[x.y.z.w]> to=<relaytest%antispam-ufrj.pads.ufrj.br@> proto=SMTP helo=<antispam-ufrj.pads.ufrj.br>
ERROR:root:Error when processing request
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/podop/postfix.py", line 104, in process_request
    result = await table.get(key)
  File "/usr/lib/python3.8/site-packages/podop/table.py", line 35, in get
    raise Exception(request.status)
Exception: 500
```

**Comment by KeepMasterBranch** [comment]
created in podop in https://github.com/Mailu/Podop/issues/7

**Comment by ghostwheel42** [comment]
Hi,
the problem is the call to `Email.resolve_domain(sender)` in the postfix_sender_access function (line 93).
The domain part of sender contains invalid IDNA characters ("[" and "]") and can't be decoded by idna.encode in IdnaDomain type decorator.
I think the internal backend functions for podop should check all input data _before_ running any operations - the input data is controlled from the ouside (via dovecot/postfix) and could trigger any kind of bad things (what about multiple "@" in the address for example).
Perhaps a simple try/except in postfix_sender_access would be a way to catch this, but I think validation is the better way to go.
Alex
