### ISSUE TITLE
Increasing the speed of our CI/CD setup

### ISSUE THREAD

**Issue by decentral1se** [Mailu/Mailu#1830]
To break off one part of https://github.com/Mailu/Mailu/issues/1828 into a separate ticket:

> 2: Future topics for CI/CD
> Last project meeting someone mentioned these topics. I think these should be discussed and tackled once we have switched to a new CI/CD provider. Possibly we could already do this when switching, but I think it takes time to make a proper decision.
> 
> 2.1: Testing, can this be reduced? Solve long build times.
> Currently a build takes takes ~30 minutes on travis. The main reason is that there are many tests. We need to thoroughly check if we really want to perform all the tests that are done currently. For this we must document what component/functionality each test tests. After that we can make an informed decision if and what can be changed. Of course it is vital that all components are still tested.
> 
> Personally I think we should first check how long a build takes on the new CI/CD pipeline and then decide if this is too long. For me 20-30 minutes is already acceptable. What max build time acceptable for you?

I think a good step forward would be for us to try and run these steps locally and understand what is taking a long time. We can use this ticket to gather our tips & tricks for what could be done to speed things up. Typically this is some parts what you are trying to achieve and other parts knowing how to hack your CI system to cache/reduce build time/etc. So, we still need to crack https://github.com/Mailu/Mailu/issues/1828.

**Comment by nextgens** [comment]
IMHO the tests can be parallelized and build artefacts should be cached/separated from configuration. That would lead to the biggest gains.

Most of the tests ensure that "known to be common" configurations don't break. Reducing the number of tests probably involves reducing the number of supported configurations.

**Comment by Diman0** [comment]
I tried using https://github.com/satackey/action-docker-layer-caching for caching the docker layer (for building) and images. This action was reliable when testing in my fork, but not reliable when used for mailu. HTTP 429 errors occurred. As a result the parallel tests could not load the images for cache. For this reason the current workflow runs all steps sequentially.

Approach 1 (only cache images)
--
I've tried a [different approach](https://github.com/Diman0/Mailu/actions/runs/975973716) where only the images are cached using actions/cache@v2. After building the images, use docker save to save all images to images.tar.gz. 
Load this file from cache for each test job and the deploy job and use docker load to load the images.

Since only a single file is cached, there should be no HTTP 429 errors.

For bors try the total time is around ~19 minutes.
For bors r+ the total time should be around ~16 minutes. For bors r+ (branch staging) the step of deploying the images is skipped. Thus also no need to spend time on retrieving the images.tar.gz file from cache.

Approach 2 (cache docker building layers, store images via artefacts)
--
I'm also going to test using https://github.com/satackey/action-docker-layer-caching for caching the builder layer. For caching the docker images I will use upload-artefact/download-artefact. This might improve the time even more.
In [this workflow run](https://github.com/Mailu/Mailu/runs/2922918479?check_suite_focus=true) you can see that loading the building layer from cache took ~2 minutes and the subsequent build took 24 seconds instead of ~10 minutes due to using cached docker layers.

I will update my post once I have results of approach 2.

**Comment by decentral1se** [comment]
Thanks for your investigation @Diman0! Really nice. I agree with your approach 1 suggestion :rocket:

**Comment by nextgens** [comment]
On #1200 there was another idea thrown around: switching to a different base image to save the time required to install python/pip and the common dependencies (socrate, curl, ...).

python:3.8-alpine3.14 is the obvious candidate... but there may be an argument for switching to something that's not alpine (and doesn't have the compatibility issues with musl - #1884 #1851 as examples of why)... and maybe even maintaining our own (overlay python:3-alpine, adding socrate and curl, use that as a base for everything).

**Comment by Erriez** [comment]
There is a strong dependency on optimizing the CI build performance before ARM can be supported, otherwise the buildtime for each PR increases too much. See #1200.

For this reason, I'll investigate first which images can be used like `python:3.8-alpine`. A challenge to keep ARM support in mind as well.

> and maybe even maintaining our own (overlay python:3-alpine, adding socrate and curl, use that as a base for everything).

Correct.

**Comment by nextgens** [comment]
@Erriez if you don't mind evaluating what a switch to a non-alpine based image would entail (speed & size-wise), that would be great too.

I've linked to https://news.ycombinator.com/item?id=22182226 on #mailu-dev

**Comment by Erriez** [comment]
Yes, will do that.

`#mailu-dev` Where can I find this channel?

**Comment by Erriez** [comment]
I've executed benchmarks by upgrading the `setup` and `docs` container and manual testing was succesful on AMD64 and Raspberry Pi 4. Now you can analyze the results what to expect when improving the CI build speed and adding ARM support:

![image](https://user-images.githubusercontent.com/8849873/127741508-580a1b9b-2781-4521-96d0-c0be7fc783fc.png)

The table above shows worst case values without caching:
* The build timing depends on download speed / system response and varies several seconds per build.
* Build time for the `setup` image increases with **~82%** by changing from `alpine` to `python3.8:alpine` with `buildx bake`.
* The image size is **~37%** smaller for `setup` and **~4%** smaller for `docs`, not so much.
* Buildx is required to build for multiple platforms.
* Benchmark on buildx includes additional setup time of a few seconds. The image size is identical to a normal Docker build.
* The build time for ARM is much higher for the `docs` image, because it is running `sphinx-build` in QEMU (building on AMD64 for platform ARM64). This is also the case when executing other (build) commands in virtual environment and depends on the image to build.

Benchmark has been performed:
* On Ryzen 7 VMWare Ubuntu 21.04
* GIT branch: https://github.com/Erriez/Mailu/tree/erriez-images-dockerfiles
* Build script: `build.sh`,
* Log: `buildlog.txt` and `Benchmarks.ods`

Upgrading the `setup` and `docs` container is a no-brainer.
Upgrading the `admin` container is a non-trivial task. I'll investigate how to upgrade other containers.

**Comment by nextgens** [comment]
> Yes, will do that.
> 
> `#mailu-dev` Where can I find this channel?

https://matrix.to/#/#mailu-dev:tedomum.net

**Comment by Erriez** [comment]
I've successfully upgraded the `docs` container in my forked branch `optimze-docs-build`:
https://github.com/Erriez/Mailu/commit/ef5c372db6af9d930aa4bfa34e3727b556e6f51d

Local machine: 
- Build on master for amd64: 35s, image size: 175MB
- Buildx for amd64 + armv7 + arm64 on branch `optimze-docs-build`: 17s, image size: 38.3MB

My multiarch images: 
https://hub.docker.com/repository/registry-1.docker.io/erriez/docs/tags?page=1&ordering=last_updated

Mailu 1.7 images for comparison:
https://hub.docker.com/r/mailu/docs/tags?page=1&ordering=last_updated

My reference documentation:

```Dockerfile
# Usage build on master:
#   # Build container from cache (or use --no-cache to force rebuild)
#   docker build -t mailu/docs:local docs
```

```Dockerfile
# Build multi-architecture 
#   # Buildx setup for multi-architecture
#   docker buildx version
#   docker buildx create --name mybuilder
#   docker buildx use mybuilder
#   
#   # Build image amd64 platform with load (for single platform)
#   docker buildx build --platform linux/amd64 --load -t mailu/docs:local docs
#
#   # Build image for amd64, armv7 and arm64 platform (--load not supported for multi platforms)
#   docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 -t mailu/docs:local docs
#
#   # Push images to Dockerhub
#   docker login
#   docker buildx build --push --platform linux/amd64,linux/arm/v7,linux/arm64 -t mailu/docs:master docs
#
#   --------------------------------------------------------
#   # Check built images
#   docker images
#
#   # Save/load built image on other target
#   docker save mailu/docs:local > mailu-docs-local.tar
#   rsync mailu-docs-local.tar user@server:/tmp/
#   docker load < mailu-docs-local.tar
#
#   # Run container local build
#   docker run -it --rm --name mailu-docs -p 80:80 mailu/docs:local
#   
#   # Run container pushed to registry
#   docker run -it --rm --name mailu-docs -p 80:80 mailu/docs:master
#
#   # Open webbrowser http://localhost/$VERSION
```

One disadvantage is that the upgraded Dockerfile requires `buildx` and is not compatible with the default `build` command.

**Comment by nextgens** [comment]
I suggest we go for incremental changes and stick with docker build until we can actually use/deploy arm builds.

Would you mind sending a PR for the containers you've already worked on?

**Comment by Erriez** [comment]
> I suggest we go for incremental changes and stick with docker build until we can actually use/deploy arm builds.

Yes, after some investigation this is feasible, for example to upgrade Dockerfiles first with current CI. The admin, rainloop and roundcube keeps me currently busy to upgrade. The admin image contains a lot of NPM high security issues which needs to be addressed as well.

> Would you mind sending a PR for the containers you've already worked on? I've done some testing and it looks like some stuff is missing to get them functional

Yes, I'll test basic images locally before creating a PR. My current branches are not ready yet.

My basic test consists of running `none, admin + CLI, nginx, dovecot, postfix, rainloop/roundcube)` by sending/receiving emails manually on real hardware. Do you have a suggestion how to test the other containers such as optional? Is there a possibility to run automated regression tests locally? I want to make sure that the original version has similar behavior with mine.

**Comment by nextgens** [comment]
In principle yes... in practice I've never got it to work the way I wanted. Check out what the CI does in https://github.com/Mailu/Mailu/blob/master/.github/workflows/CI.yml

**Comment by Erriez** [comment]
I'll stick to `node:8 assets` in `admin` image, because I'm not familiar enough with this project. Upgrading to `node:16.6.0` breaks several dependencies in `core/admin/assets`. Maybe something for a new issue to upgrade the security issues.

I used the CI before which looks like useful to create basic regression tests. However, maybe a nice to have for the future. :-)
