### ISSUE TITLE
SoGo

### ISSUE THREAD

**Issue by normanu** [Mailu/Mailu#199]
Instead of using Radicale / Rainloop & Roundcube.
Is it also possible to use SOGo as client, to have calendar & addressbook easily integrated?

**Comment by kaiyou** [comment]
I am not sure how SoGo would integrate in the current landscape. Does it come with its own CalDav implementation? If so, I would rather stick with Radicale, which is a lot simpler to manage and compatible with multiple clients.

If SoGo is "just another client", sure it possible to integrate. If you have experience with it, feel free to start working on an implementation.

**Comment by kevinbader** [comment]
Afaik SOGo integrates with existing MTA and MDA servers, but contains its own adressbook and calendar implementation. It comes with support for ActiveSync/Exchange, which is awesome and apparently missing in the current setup.
SOGo also brings its own mail client to the table, but since it caters any CalDAV/CardDAV clients, using it is in no way required.

**Comment by F0rth** [comment]
mailcow is already packaging SoGo in docker containers, perhaps some ideas to borrow @normanu  ?

**Comment by normanu** [comment]
This was a very old issue, I'll close it.

**Comment by kaiyou** [comment]
It is vert old but very current as we were discussing this yesterday. Reopening.

**Comment by normanu** [comment]
Ah I'm currently running mailcow be a use of SoGo.
Didn't see it was the Mailu GitHub......

**Comment by rgarrigue** [comment]
I'ld be happy to have sogo instead of both roundcube or rainloop. They're lacking as webmail from mobile to say the least, and the calendar & contacts integrated are nice too

**Comment by cedvan** [comment]
up ?

**Comment by Dunky13** [comment]
Any updates on this? I'm looking to switch from mailcow since it has to run on a separate instance and can't run in a Docker Stack... =_= 
Mailu seems interesting if/once I can use activesync.

**Comment by ticteam** [comment]
any update on this ?

**Comment by kaiyou** [comment]
Not recently. Help is welcome though. The hard part is that SoGo is a beast that ships with many features embedded, so binding them to Mailu is not an easy matter.

**Comment by codeagencybe** [comment]
Any update or progress on this?
I'm also waiting for SoGo.
Currently using Mailcow but it lacks proper support for Docker stack and Kubernetes. So I want to consider a switch to Mailu but I need the SoGo webmail client. 

Can you let us know what the bottleneck or issues are? Where are you stuck? Perhaps I can help.

Thanks!

**Comment by muhlemmer** [comment]
Hi, I had a colleague investigating this and I forgot to post the outcome.

SoGo is by itself a groupware server which handles authentication by directly accessing a relational DB (SQL) or an LDAP server.

1. In order to integrate SoGo (or any other product) it should be able to offload authentication to Mailu over any of the supported protocols, like IMAP, SMTP or HTTP (podop). So unless we missed something, SoGo can't easily be integrated with the current Mailu design.
2. SoGo works as a proxy for IMAP and SMTP, which is in conflict with our current Nginx based design.

**Comment by kaiyou** [comment]
I am closing this as it looks near-to-impossible and we should not keep hopes up by keeping the issue open :)
