### ISSUE TITLE
Received header does not mention TLS

### ISSUE THREAD

**Issue by kkretsch** [Mailu/Mailu#2004]
I have some warning within rspamd that the last received line does not mention TLS (RECEIVED_NO_TLS_LAST) which made me nervous at first.
I manually submitted an email from another host using gnutls-cli and used manually that STARTTLS stuff. I could transmit an email this way, but the Received header inserted by postfix still only says smtp like here

```
Received: from www9.example.com (www9.example.com [1.2.3.4])
	by mail2.example.com (Postfix) with ESMTP id EEF9ABDD8F
	for <kai@example.com>; Wed,  6 Oct 2021 14:37:31 +0000 (UTC)
```

I would have expected something like

```
Received: from [37.201.193.1] (helo=smtpclient.apple)
	by smtprelay08.example.com with esmtpsa  (TLS1.2) tls TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
	(Exim 4.94.2)
	(envelope-from <kai@example.com>)
	id 1mY7WH-000350-LT
	for kai@example.com; Wed, 06 Oct 2021 16:03:41 +0200

```
So to see the ESMTPSA instead only ESMTP.

I even added that override line to mailu postfix:

`smtpd_tls_received_header = yes
`
which ends up in the main.cf but makes no difference.

Anyone else having the same problem with the missing TLS information in the received headers and therefore rspamd giving alerts?

PS: Using the 1.8 mailu

**Comment by nextgens** [comment]
This is a known problem, see #1705

**Comment by kkretsch** [comment]
For the rspamd it might be a known problem, but I still miss the way it will find the TLS information if there is no Received header mentioning it at all. Any hint on this?

**Comment by nextgens** [comment]
It's a different face of the same problem: as it stands postfix doesn't know what nginx has negotiated... that's what needs fixing; once it's fixed, logging the details will just be about enabling ``smtpd_tls_received_header``.

You could configure nginx (in the front container) to log the details of the handshake (but that would be in the server logs rather than in the message itself) or use 3rd party tools such as ssldump (assuming your requirement is temporary).
