### ISSUE TITLE
Status of alternative database backends

### ISSUE THREAD

**Issue by rit001** [Mailu/Mailu#2068]
{Enhancement request}

The docs under "Changing the database back-end" section state "This functionality should still be considered experimental!", but that statement was written 3 Dec 2018 and so it is not clear what the current position is regarding using alternative backends with the current 1.8 release.

I did come across thread #1217 where the idea of shipping images with alternative databases was discussed and the idea was (in my opinion rightly) declined as such work is outside the core project scope.  One logical way forward would be for Mailu to sense which database engine it has been linked to and then create its required database using information passed within the docker-compose file - if the details of a database admin account are provided then auto-creation is allowed.

**Comment by Diman0** [comment]
Mailu fully supports SQLite, MySQL/MariaDB and PostgreSQL. That message was initially a warning. 
In the next release the warning message will be removed. See the updated database page (https://mailu.io/master/database.html). Just like any other software program you only have to provide the connection details for an empty database.

One tip. Roundcube does NOT offer any possibility for migrating from one database system to another (E.g. from SQLite to MySQL). Mailu does support this for the Mailu database. So you must think carefully what database back-end you want to use for roundcube (assuming you want to use roundcube instead of rainloop).
