### ISSUE TITLE
password authentication failed for user "roundcube"

### ISSUE THREAD

**Issue by parsifallo** [Mailu/Mailu#2082]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
```
1.8
```

## Description
If I choose roundcube as webmail gui, roundcube won't start with the error message below. If I switch to `rainloop` (use rainloop image and set `WEBMAIL=rainloop`) everything's fine.

## Replication Steps
- Create setup via setup script
- Choose roundcube as webmail
- `docker-compose up -d`

## Expected behaviour
Roundcube webmail should start

## Logs
```
Initializing database
ERROR: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "roundcube"
ERROR: Failed to connect to database
```

**Comment by Diman0** [comment]
You suggest you use SQLite, but this error only occurs when a different database flavour than SQLite is used.
I cannot replicate the error with your replication steps.
Please provide all ROUNDCUBE_DB_* and DB_* variables from your mailu.env file (do not share the passwords). This error suggests it is incorrectly configured.

**Comment by parsifallo** [comment]
Thank you for your reply.
```
###################################
# Database settings
###################################
DB_FLAVOR=postgresql
DB_USER=<USER>
DB_PW=<PASSWORD>
DB_HOST=db
DB_NAME=<DB>


ROUNDCUBEMAIL_DB_TYPE=postgresql
ROUNDCUBEMAIL_DB_HOST=db
ROUNDCUBEMAIL_DB_PORT=5432
ROUNDCUBEMAIL_DB_USER=<USER>
ROUNDCUBEMAIL_DB_PASSWORD=<PASSWORD>
ROUNDCUBEMAIL_DB_NAME=<DB>
```

I tested it with `ROUNDCUBEMAIL_DB_TYPE=sqlite` also but same error message. `DB_USER`is in both cases not `roundcube`

**Comment by Diman0** [comment]
Your replication steps are incomplete. You are not using SQLite. 
The problem is a wrong parameter in the mailu.env file.
It is not `ROUNDCUBEMAIL_DB_TYPE=postgresql`, but  `ROUNDCUBE_DB_FLAVOR=postgresql`
See https://mailu.io/master/configuration.html#database-settings

For the logic see https://github.com/Mailu/Mailu/blob/1.8/webmails/roundcube/start.py

After changing mailu.env, you must recreate (not restart) all containers. This should happen automatically with `docker-compose up -d`, but as a precaution you could run `docker-compose down && docker-compose up -d`.

From Mailu 1.9 this can also be properly configured via setup.mailu.io. You don't have to manually configure this in mailu.env which can lead to typing errors. The PR #2069 for this improvement is waiting for review.

**Comment by parsifallo** [comment]
Thank you very much! Currently using `ROUNDCUBE_DB_FLAVOR=sqlite` but I guess I will change this to `postgresql` later on. I'll close this ticket
