### ISSUE TITLE
Server with multiple ip addresses

### ISSUE THREAD

**Issue by BirknerAlex** [Mailu/Mailu#219]
Hello,

I'm running a CentOS 7 server with multiple ip addresses. One of them (example 10.0.0.1) is for the mailu server. I've set it as BIND_ADDRESS, this works so far. All mailu services are reachable under this ip address, but postfix sends all emails with the primary ip (example 10.0.0.2) address (default gateway).

The IP 10.0.0.1 is set in SPF records and has a PTR record (mail.domain.com). But the outgoing emails are sent by mail.domain.com with the 10.0.0.2 ip address. That causes that the mails got blocked by some mail providers because PTR record and ip does not match.

How can I tell postfix which ip address should be used from the host?

I think this can be tricky because the Docker container doesn't know the available ip addresses of the host and docker is using the main ip as source ip. I'm not sure if this can be overwritten from inside the container.

Maybe the only way is to put the mailu docker containers into a virtual machine with only one single ip.

**Comment by kaiyou** [comment]
Unfortunately, due to the way Docker default configuration manages outgoing connections, I have not been able to find a simple solution for this issue. Currently, on the servers that require multiple IP addresses, I simply add a `POSTROUTING` rule in iptables or nftables so that outgoing traffic to destination port 25 is mapped to the proper IP address.

This works pretty good but still has some noticeable drawbacks: if another container is compromised and starts sending spam from your host, your email IP address will quickly be blacklisted by major providers for instance.

**Comment by gadicc** [comment]
Can't we just - rather than matching on outgoing port 25 - match against the source docker subnet (that we specify in `mailu.env`)?  I ran:

```bash
iptables -t nat -D POSTROUTING -s 192.168.203.0/24 ! -o br-86dee -j MASQUERADE  # remove existing rule
iptables -t nat -A POSTROUTING -s 192.168.203.0/24 ! -o br-86dee -j SNAT --to-source <DESIRED_OUTGOING_IP>
```

and now outgoing mail originates from that IP and SPF passes.

I think if we modify the `docker-compose.yml` like:

```yaml
networks:
  default:
    driver: bridge
    driver_opts:                                               # <--
      com.docker.network.bridge.enable_ip_masquerade: 'false'  # <--
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```

docker won't create the first rule in the first place but I need to spend a bit more time testing.  And to pick the best way to automate creating the replacement rule (with correct bridge interface name).

I'll report back when I have a chance to look at this again... of course if anyone has any of their own insight it will be very welcome.

Helpful reference on the rules: https://medium.com/@havloujian.joachim/advanced-docker-networking-outgoing-ip-921fc3090b09

**Comment by gadicc** [comment]
In case this is still of interest to anyone, I updated my comment above with my final setup.
