### ISSUE TITLE
Mailman 3 integration?

### ISSUE THREAD

**Issue by stevelord** [Mailu/Mailu#220]
Has anyone tried setting up a list manager like Mailman?

Mailman 3 apparently uses docker as a base, but it looks like it may have it's own postfix server. Before I experience the horror that is trying this first hand, I was wondering if anyone else has given it (or any other mailing list manager) a go successfully?

I suspect that any mail server that integrates with postfix is going to either conflict with mailu's postfix at some level or will need to carry a map file of some sort across.

Any thoughts/suggestions/experiences? Is it worth integrating a mailing list server into mailu?

**Comment by kaiyou** [comment]
For this to work properly on the same public IP address, you must run both on the same Docker network (or with a Docker network in common), and have only one of the Postfix servers to listen publicly.

The expected behaviour would probably be to have Mailu listen on the public IP address and redirect mails to Mailman's Postfix. Unfortunately, Mailu does not yet have an option to redirect emails for a specific domain to a given MX. One would have to implement this first (should be quite simple though).

**Comment by Archie1978** [comment]
stevelord use a BIND_ADDRESS variable in the .env.
If you are many IP, you must separate with coma.

I have a 20 dockers and it is a mess :)

**Comment by kaiyou** [comment]
I will try and implement a dynamic domain routing table for this to work properly in the future. It will probably land in `1.5`.

**Comment by kaiyou** [comment]
I started implementing this on branch `feature-relays`. Currently only the admin interface part is implemented.

**Comment by kaiyou** [comment]
You can now integrate with Mailman using relays, as they were just merged. Closing this issue!
