### ISSUE TITLE
Certbot autorenew fails

### ISSUE THREAD

**Issue by xamanu** [Mailu/Mailu#223]
I'm repeatedly having issues with the certificate creation. I report here, maybe it may help anybody else also.

**Situation:**

Certificates are not renewed. Tested on `stable`, `latest` and `1.4`.
(btw, I replaced my domain with mail.example.com)

`$ docker-compose log -f admin`
```
admin_1      | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
admin_1      | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
admin_1      | Generating TLS certificates using Certbot
admin_1      | Error while generating certificates:
admin_1      | 
admin_1      | [2017-07-20 06:37:15 +0000] [18] [INFO] Starting gunicorn 19.7.1
admin_1      | [2017-07-20 06:37:15 +0000] [18] [INFO] Listening at: http://0.0.0.0:80 (18)
admin_1      | [2017-07-20 06:37:15 +0000] [18] [INFO] Using worker: sync
admin_1      | [2017-07-20 06:37:15 +0000] [28] [INFO] Booting worker with pid: 28
```

This is the old certificate "privkey1.pem":
`$ $ ls -al data/mailu/certs/live/mail.example.com`
```
total 12
drwxr-xr-x 2 user user 4096 Jul 20 08:35 .
drwx------ 4 user user 4096 Apr 20 19:07 ..
lrwxrwxrwx 1 user user   42 Apr 20 19:07 cert.pem -> ../../archive/mail.example.com/cert1.pem
lrwxrwxrwx 1 user user   43 Apr 20 19:07 chain.pem -> ../../archive/mail.example.com/chain1.pem
lrwxrwxrwx 1 user user   47 Apr 20 19:07 fullchain.pem -> ../../archive/mail.example.com/fullchain1.pem
lrwxrwxrwx 1 user user   45 Jul 20 08:35 privkey.pem -> ../../archive/mail.example.com/privkey1.pem
-rw-r--r-- 1 user user  543 Apr 20 19:07 README
```
There are a lot of new, but empty keys, for the renewal attempts:

`$ ls -al data/mailu/certs/archive/mail.example.com`
```
total 24
drwxr-xr-x 2 user user 4096 Jul 20 04:00 .
drwx------ 4 user user 4096 Apr 20 19:07 ..
-rw-r--r-- 1 user user 1805 Apr 20 19:07 cert1.pem
-rw-r--r-- 1 user user 1647 Apr 20 19:07 chain1.pem
-rw-r--r-- 1 user user 3452 Apr 20 19:07 fullchain1.pem
-rw-r--r-- 1 root root    0 Jun 29 04:00 privkey10.pem
-rw-r--r-- 1 root root    0 Jun 30 04:00 privkey11.pem
-rw-r--r-- 1 root root    0 Jul  1 04:00 privkey12.pem
-rw-r--r-- 1 root root    0 Jul  2 04:00 privkey13.pem
-rw-r--r-- 1 root root    0 Jul  4 04:00 privkey14.pem
-rw-r--r-- 1 root root    0 Jul  5 04:00 privkey15.pem
-rw-r--r-- 1 root root    0 Jul  6 04:00 privkey16.pem
-rw-r--r-- 1 root root    0 Jul  7 04:00 privkey17.pem
-rw-r--r-- 1 root root    0 Jul  8 04:00 privkey18.pem
-rw-r--r-- 1 root root    0 Jul  9 04:00 privkey19.pem
-rw-r--r-- 1 user user 1704 Apr 20 19:07 privkey1.pem
-rw-r--r-- 1 root root    0 Jul 11 04:00 privkey20.pem
-rw-r--r-- 1 root root    0 Jul 12 04:00 privkey21.pem
-rw-r--r-- 1 root root    0 Jul 13 04:00 privkey22.pem
-rw-r--r-- 1 root root    0 Jul 14 04:00 privkey23.pem
-rw-r--r-- 1 root root    0 Jul 15 04:00 privkey24.pem
-rw-r--r-- 1 root root    0 Jul 16 04:00 privkey25.pem
-rw-r--r-- 1 root root    0 Jul 18 04:00 privkey26.pem
-rw-r--r-- 1 root root    0 Jul 19 04:00 privkey27.pem
-rw-r--r-- 1 root root    0 Jul 20 04:00 privkey28.pem
-rw-r--r-- 1 user user    0 Jun 20 04:00 privkey2.pem
-rw-r--r-- 1 user user    0 Jun 21 04:00 privkey3.pem
-rw-r--r-- 1 user user    0 Jun 22 04:00 privkey4.pem
-rw-r--r-- 1 user user    0 Jun 23 04:00 privkey5.pem
-rw-r--r-- 1 user user    0 Jun 24 04:00 privkey6.pem
-rw-r--r-- 1 user user    0 Jun 25 04:00 privkey7.pem
-rw-r--r-- 1 user user    0 Jun 27 04:00 privkey8.pem
-rw-r--r-- 1 root root    0 Jun 28 04:00 privkey9.pem
```

I also updated certbot with

`$ docker-compose exec admin bash`
`$ pip install certbot --upgrade`

Looking into the /tmp/letsencrypt.log has become difficult. Because I removed and rebuilt the images and letsencrypt (the logs are not persistent) and now certbot gives me the problematic error:

> acme.messages.Error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new cert :: too many certificates already issued for exact set of domains: mail.example.com

It seems like, mailu's misbehavior on renewing certificates has lead to the point that letsencrypt doesn't allow to get new certificates. Thanks for your time!

**Comment by trikpat** [comment]
I have expererienced the same thing, but I also lost the logs.
In the end I patched certbot.py to only run in "dry-run" mode for a day or so. 
After that I stopped (docker-compose down) the whole set, removed the contents of the "certs"directory and restarted (docker-compose up -d).
Now its got brand new certs etc.

**Comment by kaiyou** [comment]
Okay, thank you for reporting this again. It seems indeed that Mailu tries to renew way too often and that causes rate limits to kick in. I will try and simply lower the refresh time, I really thought that certbot wasn't even trying to contact the servers if the certificate was recent enough.

**Comment by nils-wisiol** [comment]
I do belive @kaiyou commit won't fix the problem (at least not for me). 

I ran into a similar problem: my mailu certificates were out of date. However, the certificate transparency log showed that let's encrypt issued certificates for my hostname.

I downloaded the most recent certificate for my hostname from the transparency logs. Using the modulus, I was able to find the corresponding private key in the mailu `certs` directory. However, it was stored in `certs/keys` rather than in `certs/live/myhostname.com/privkey.pem`.

Hence, I can confirm the certificate was issued on my request, but something went wrong subsequently in the process of storing and replacing the live certificate. Unfortunately, I also lost the logs in the admin container, so I can't really tell what went wrong.

I believe the LE limit for issuing certificates is 5/week in a sliding window, so the next chance will come soon.

@kaiyou Maybe it makes sense to use the certbot `renew` command instead of `certonly` to have certbot only renew 30 days before expiry.

**Comment by nils-wisiol** [comment]
@xamanu would you be able to check the public transparency logs to see if certificates were issued for your hostname?

**Comment by kaiyou** [comment]
@nils-wisiol it would make perfect sense indeed. I have to add some logic so that the cert is renewed if already existing, but my expertise with certbot is quite limited. Do you have any good pointers for such implementations?

**Comment by kaiyou** [comment]
See #250 for long term plans regarding Certbot, I probably will stop working on this issue as a consequence.

**Comment by kaiyou** [comment]
Finally, 53c3153229da98afa94a3cbce4c78e19df05a369 has a proper solution that simply does not require to run `certbot` manually anymore. It requires that the `traefik` reverse proxy is used instead of nginx, which is probably going to become the default.

I am closing this and inviting you to comment in #250 for feedback on the new implementation.
