### ISSUE TITLE
Provide auto-configuration files

### ISSUE THREAD

**Issue by nalt** [Mailu/Mailu#224]
Modern mail clients attempt auto-configuration to greatly simplify the setup process. Mainly they use XML files requested via http.

Can this be included in mailu? It shouldn't be much effort - an XML template, SSI and the nginx config might be enough.

**Comment by kaiyou** [comment]
What do you mean SSI? Anyway I think this could indeed be handled in the current version using `302` to the admin interface and generating the cert there. However, how does the MUA query the XML for a given domain if that domain only exposes a `MX` record?

**Comment by nalt** [comment]
Thunderbird checks e.g. autoconfig.<domain>. If the name cannot be resolved, autoconfig fails. Needs to be checked if a 302 is ok. The process is described in https://www.ullright.org/ullWiki/show/providing-email-client-autoconfiguration-information-from-moens-ch .

SSI is like a simple template language handled by the server. But it's very old.

There is also a project, automx.org, but that's probably overkill.

**Comment by kaiyou** [comment]
Well, this sounds a bit more complex than I originally expected. First, we have to handle certificates properly: we can't have domain certificate for every `autoconfig.<domain>` generated automatically, so we should check if a `CNAME` on autoconfig will do the trick or if maybe Thunderbird can rely on the MX record or any other SRV record.

Also, implementation for Outlook seems completely different.

**Comment by kaiyou** [comment]
Could this be partially implemented if we integrate with z-push for Outlook integration?

**Comment by HorayNarea** [comment]
I'm looking currently looking into this, at least Mozilla-compatible auto-config seems very easy because:
- CNAMEs are fine
- HTTP-redirects are fine
- even non-HTTPS is fine (but i hope we all agree that it should not be done this way…)
- it's basically just a static XML-file (real-life example in production: https://autoconfig.lynx.uberspace.de/mail/config-v1.1.xml?emailaddress=myname@example.com)

**Comment by kaiyou** [comment]
So, a simple CNAME for `autoconfig.`` on the domain (and zone configuration provided on the details page), and a ``/mail/config*`` endpoint on both the frontend and admin container could actually do the trick. All configurations would be identical I guess, so it's pretty stateless and simple to implement.

**Comment by kaiyou** [comment]
If anyone want to give it a go, please PR. Otherwise, I will start working on this after ``1.5.1`` is properly released :)

**Comment by HorayNarea** [comment]
Disclaimer: I don't know if all clients that claim/seem to support [Mozilla-compatible auto-config](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration#Configuration_server_at_ISP) actually do implement it the way Mozilla has "standardized" it :grinning:

**Comment by HorayNarea** [comment]
The [specification for the fileformat](https://wiki.mozilla.org/Thunderbird:Autoconfiguration:ConfigFileFormat) says that a literal `%EMAILADDRESS%` is enough for the `<username>`, so it can really be a static file

**Comment by xamanu** [comment]
I gave it [a try](https://github.com/Mailu/Mailu/compare/master...xamanu:automx) with automx. I don't think it is an overkill. It is a pretty small script and covers not only the here discussed `autoconfig` mechanism following Mozilla, but also support Microsoft's `autodiscovery` and Apple's `mobileconfig`. So, instead of reinventing the wheel, we can just take this software, similar to the other pieces that are assembled in Mailu (radicale, clamav, roundcoube, etc...).

The missing piece is the proper nginx configuration for the `front` container. I have still some problems with this one, then it could become a proper pull request.

**Comment by benyanke** [comment]
This would be killer - definitely following this.

**Comment by kaiyou** [comment]
I just reviewed your branch and it looks pretty good. The only part that bothers me is automx connecting to the user database. Isn't possible to authenticate first in nginx, and then only forward to automx to generate the configuration files?

**Comment by xamanu** [comment]
We can avoid connecting to the database and just provide the regular connection settings in the config file. This is straight forward and I' m happy to adjust my code and bring it into a PR.

The downside is, that individual users selection whether to use IMAP and/or POP3 will not be taken into consideration and I fear that this can lead to confusion on the side of the user. When e.g. IMAP is not allowed but the auto discovery proposes this as the working configuration.

**Comment by kaiyou** [comment]
I just had a look at automx code and here is the dilemma: I was hoping to be able to just use part of it as a lib since it is Python, but the code itself is an absolute nightmare; on the other hand, it just works fine and has enough followers to ensure proper support.

Here is my current take on the matter: tomorrow, I'll merge your work except for the database access and use static configuration for now. Then, we can try and implement a script or custom backend that just queries an API to get the settings from the admin container.

**Comment by kaiyou** [comment]
Okay. I just spent an hour trying to simplify things and basically got to the conclusion automx code was too complex for the purpose and there are probably useful libraries we can include directly in the admin container.

**Comment by muhlemmer** [comment]
Is this really a work in progress, like is there a branch with development code somebody can pickup? Or de we need to start this from the ground up?

I'll remove the status/wip label for now, please re-instate if necessary. (I'm cleaning up the 1.6 milestone)

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by benyanke** [comment]
Not stale

**Comment by benyanke** [comment]
not stale!

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

**Comment by xamanu** [comment]
Thanks a lot @Diman0 for picking up the good work on Mailu! Just wanted to send you a big ❤️ and say that it is completely understandable, that you are sorting out issues. I think you are doing a great work with the questionnaires and friendly messages. I also agree on the selection you are doing on the issues I'm following.

Again, thanks a lot and don't let you feel bad for the loud people complaining and not supporting!

Peace

**Comment by creepinson** [comment]
So autoconfig won't be added to mailu? Thunderbird keeps saying "failed to find the settings" and I don't know what to do.
