### ISSUE TITLE
Your ClamAV installation is OUTDATED!

### ISSUE THREAD

**Issue by nike7o0** [Mailu/Mailu#2320]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
MASTER

## Description
The Clamav container is outdated.
Maybe you should think abount using the official clamav image - https://hub.docker.com/r/clamav/clamav

## Logs

antivirus_1  | Tue Apr 12 12:01:35 2022 -> WARNING: Your ClamAV installation is OUTDATED!
antivirus_1  | Tue Apr 12 12:01:35 2022 -> WARNING: Local version: 0.103.3 Recommended version: 0.103.5

**Comment by leolivier** [comment]
Same here (but the official image is supporting only amd64 which does not fit the needs of a lot of Raspberry Pi users)

**Comment by henniaufmrenni** [comment]
The issue is, that in the Alpine 3.14 package repository, the ClamAV version is  [0.103.3-r0 ](https://pkgs.alpinelinux.org/package/v3.14/community/x86/clamav) while in the 3.15 repository the ClamAV version is [ 0.104.2-r0 ](https://pkgs.alpinelinux.org/package/v3.15/community/x86/clamav). The Alpine package repository is not-deterministic - [see here](https://gitlab.alpinelinux.org/alpine/abuild/-/issues/9996#note_87135) -  meaning one cannot pin the package version. Since the Mailu ClamAV container is rebuild with every release, this could mean, that the ClamAV version "silently" changes between Mailu releases. The only real option to solve this, is to build ClamAV from source or change the base image to one with a package manager that supports version pinning, like Debian. This would also allow to freely choose the ClamAV version and for example stay on the 0.103 [LTS](https://blog.clamav.net/2021/09/changes-to-clamav-end-of-life-policy.html) version number longer.
