### ISSUE TITLE
No mail being sent 

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#245]
After I upgraded Mailu recently, the server isn't sending mail.

smtp_1       | postfix/smtp[95]: connect to alt2.gmail-smtp-in.l.google.com[2607:f8b0:4003:c05::1a]:25: Network unreachable

I think it is an IPv4/IPv6 issue.

https://www.digitalocean.com/community/questions/can-not-send-any-email-from-postfix

Can anyone advise how to try to resolve this on mailu?

**Comment by kaiyou** [comment]
If your container have IPv6 addresses, outgoing traffic should be routed properly. Otherwise Postfix will try to send outgoing email over IPv6 and fail.

If you are hosting Mailu on a host that you can configure, simply disable IPv6 on the Docker network, or fix the routing problem so that outgoing IPv6 traffic properly reaches the destination server.

**Comment by SaiGonSeamus** [comment]
This was a hosting issue.
