### ISSUE TITLE
Small feature - add mailu version in the admin UI 

### ISSUE THREAD

**Issue by skironDotNet** [Mailu/Mailu#2570]
Add mailu version in the admin UI 
I think it would nice to be able to see which version of mailu we are running, unless there is other simple way?

Thanks

**Comment by nextgens** [comment]
If you run a recent-enough version of Mailu you can use:
``docker-compose exec admin cat /version`` or should be able to see which image are running using ``docker ps``.

**Comment by elandorr** [comment]
I suggest a different approach altogether.

Broken updates have caused me great pain several times in years past. I was only saved by luck, since I hadn't updated in a while, and a new major release was available that fixed it. (God forbid you get stuck at the wrong time!) That's because you used to not be able to select specific versions. That changed a while ago. Now you can override it by setting an environment variable.

I simply made a small update script:
```bash
export MAILU_VERSION=1.9.43
docker compose pull
docker compose down
docker compose up -d --force-recreate
docker compose logs -f
```

The additional `down` is probably overkill, but some earlier releases had issues when not fully down-ed, so I kept it.

It sounds like you update automatically, I'd personally recommend against that. Hence the logs line. I want to do a sanity check before considering it done.

How to find a changelog is explained on the release page. I'm guilty of not always reading it myself, though. :)

Cheers
