### ISSUE TITLE
Feature request - Migration Tool

### ISSUE THREAD

**Issue by pappastech** [Mailu/Mailu#2573]
I'm looking for a feature that when configured to look at a previous e-mail server, would log into that old e-mail server and retrieve a copy of all user's e-mail.

- This would be a tool configured temporarily when migrating from one e-mail server to Mailu
- The tool would only start fetching e-mail from the old server when a user logs into Mailu
- The tool would retrieve e-mail via IMAP to make it not dependent on the architecture of the old e-mail server
- For a reference, MailEnable has this feature and it works great

Thanks,
Tom

**Comment by Diman0** [comment]
Did you check the documentation?
Fetching emails from a different email server can be configured on the [Fetched accounts page](https://mailu.io/1.9/webadministration.html#fetched-accounts).

If this functionality does not fit your preference, you could spin up your own fetchmail container, or use a tool like [imapsync](https://github.com/imapsync/imapsync).

**Comment by pappastech** [comment]
Yes, I looked at the documentation and I understand I could probably come up with a way to do this on my own. I was suggesting a feature addition to this project as a means to simplify migration from other platforms. If it's outside the scope of what the project wants to do, I understand.

**Comment by Aquariu** [comment]
Dear all,

I'm planning a migration from a "hand-configured" postfix/dovecot setup to Mailu. (In that process, I've the Mailu install on, say,  mailu.exemple.org and my "legacy" install on exemple.org)
In that regard, the question from OP are interesting to me and I also failed to find what I believe I needed in the documentation.

Ideally I would have liked either:
- In the docs, the documentation of mail storage format so that I can copy/paste user mail folders (I store in Maildir) and probably use the [user-import function](https://mailu.io/master/cli.html#user-import) 
- A first login wizard on the web interface to request the old server credentials to copy the complete Inbox (like Imapsync) and then swap domains.

I understand that  [config import](https://mailu.io/1.9/cli.html#config-import)  is only about configuration and not INBOX migration. If I'm wrong then I apologize.

Kind regards,

Olivier

**Comment by nextgens** [comment]
If you are already using dovecot you should use https://wiki.dovecot.org/Tools/Doveadm/Sync
