### ISSUE TITLE
DNS DKIM entry is broken up in two parts (for 2048b keys), making it error-prone

### ISSUE THREAD

**Issue by tusooa** [Mailu/Mailu#2618]
### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: 1.9

## Description

DNS DKIM entry in mailu-admin is broken into two parts for 2048b keys.

## Replication Steps

1. Set up a mail domain
2. Generate keys in admin
3. Observe DNS DKIM entry

## Observed behaviour

```
[...] 600 IN TXT "v=DKIM1; k=rsa; p=[.....]" "[......]"
```

(the " " in between is hard to notice, and easily make people just copy that into the dns configuration, rendering the dkim entry invalid)

## Expected behaviour

```
[...] 600 IN TXT "v=DKIM1; k=rsa; p=[.....][......]"
```

(shouldn't be broken up into two parts)

## Logs

not relevant

**Comment by ghostwheel42** [comment]
@tusooa You can read here https://www.mailhardener.com/blog/how-to-enter-txt-values-in-google-cloud-dns why we do this intentionally.
Maybe adding a toggle which splits/joins the field (using javascript) would be a solution for everyone.

**Comment by nazar-pc** [comment]
Hm... making it break everywhere in order to not break in Google Cloud DNS is a bit suboptimal (especially because those are reported as bugs there and were not closed by Google).

I'd add instructions on how to split to FAQ instead (there are apparently tools like https://www.mailhardener.com/tools/dns-record-splitter for this) and leave it contiguous the way it should be for everyone else.

**Comment by migs35323** [comment]
As a new user, i lost an entire day troubleshooting this issue..
kubernetes user here btw
i was trying to setup the entries in a cloudflare dns manually, i was not really sure the correct way it was supposed to be inserted..

i eventually found out somewhere that i could paste the entries in a text file and upload to cloudflare and it created the correct entries... 
maybe at least we could get a button to generate the text file so we can just import the entries into the dns provider?

or better yet if the correct implementation is only to solve an issue with 1 specific dns provider, make the default "the default"
maybe put a note for that specific provider..

i also wanted to leave a note, probably should create my own issue...
in the same page the MX entry has a green mark saying its "ok"
for some time while troubleshooting i was hoping the other entries showed up with a green mark as well

**Comment by ghostwheel42** [comment]
I'm currently compiling a PR with interfaces changes (auto-focus of form fields, better navigation, dns validation, ...)
I'll add the non-splitted version there (show both or make toggling possible, sth like this.)

For now you can output all the keys using the config-export (which makes it easy to automate the update using a dns api):
```
docker compose exec admin flask mailu config-export -jd domain | jq -r '.domain[] | select(.dkim_publickey) | "dkim._domainkey.\(.name). 600 IN TXT \"v=DKIM1; k=rsa; p=\(.dkim_publickey)\""'
```

**Comment by ghostwheel42** [comment]
@nazar-pc Hi, I'm just coming back on this.

I did not "break" the key into parts because of google, but because of DNS itself, as TXT records [can have up to 255 characters](https://www.freesoft.org/CIE/RFC/1035/9.htm) and for TXT records that include more than 255 characters, DNS adds multiple strings together in a single record.

Most Interfaces and APIs hide this from the user.

**Comment by nazar-pc** [comment]
I've got it working, so not an issue for me (not anymore), but others may hit it too, so documentation and/or UI improvements would be helpful for future users.
