### ISSUE TITLE
Error pull traefik in Stable

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#265]
Hi, 
I'm getting this when I pull stable with traefik in it after the the last PR.

```
Pulling http (mailu/traefik:stable)...
ERROR: manifest for mailu/traefik:stable not found
```

**Comment by SunMar** [comment]
Hi,

Traefik is only just merged into ```latest``` (replacing Nginx), it's not in ```stable``` yet, you will either need to bump to ```latest``` or use ```nginx```.

I noticed this yesterday as well, the documentation notes that Traefik is for version 1.5, stable is currently 1.4. Maybe that can be clarified a bit better in the documentation, that you need to use specifically Nginx for 1.4 and Traefik for 1.5 and if you use the wrong one you get an error like that.

I didn't test this but from the setup I think if you're in 1.5 you actually can choose Nginx and it will pull in an Nginx container since on Docker Hub there still is a ```latest``` tag for Nginx, even though in the ```master``` branch the container was removed. In my opinion if the Nginx container is removed from ```master``` it means it won't be maintained anymore in ```latest``` and you shouldn't be able to choose it when using ```latest``` either, so the Docker Hub tag for ```latest``` on ```mailu/nginx``` should be removed too to prevent issues. Or the Nginx container should be added back and maintained to give a choice.

**Comment by kaiyou** [comment]
Documentation could be improved indeed. `traefik` will be available in stable mid-october, as I (very arbitrarily) placed the `1.5` release at that date.
