### ISSUE TITLE
Consider switching away from newsfragments

### ISSUE THREAD

**Issue by nazar-pc** [Mailu/Mailu#2653]
I found `newsfragments` extremely inconvenient.

It is basically impossible to understand what is going on in Mailu in terms of development with reasonable effort when changes are scattered across numerous single-line files named randomly (after PR number). There is basically no way for normal humans to quickly see what happened between 1.9.46 and 1.9.47 exactly. I have never seen such approach in other projects and I'm honestly happy that I didn't.

Moreover, current releases are built from 1.9 branch if I read it correctly, yet release notes recommend to go check `newsfragments` in `master` branch, which is not helpful as it has nothing to do with 1.9 branch even though some fixes are backported (even then, PR numbers of backports are different).

I guess those files are somewhat convenient for machine processing, but consider updating normal changelog file with patch releases for humans too.

**Comment by nextgens** [comment]
towncrier entries are currently only processed into a changelog for major releases. You have a point when you say that they ought to be done for point releases too...

The code is at https://github.com/Mailu/Mailu/blob/46429ab247d2a655a0e30db24789dd76e580a732/.github/workflows/build_test_deploy.yml#L504

Patches are welcome.

**Comment by Diman0** [comment]
This is due to the introduction of minor releases. First we would simply create updated 1.9 images when there was a backport. No information was shared at all that there was a new version. Backports are only meant for bug fixes.

Some people requested separate docker images so that they can choose when to update to a newer  minor version. This also allows to go back to a previous minor version.

Having to check the towncrier newsfragments is a consequence of this. It is an automated process. Maybe the process could be enhanced to include the towncrier entry from the pull request that triggered the release?

You are free to provide a patch for this.

**Comment by nazar-pc** [comment]
I have never dealt with Towncrier before (in fact I only became aware of it thanks to this issue), but I might end up tackling this eventually.
