### ISSUE TITLE
Large disk usuage (xapian-indexes)

### ISSUE THREAD

**Issue by kale1d0code** [Mailu/Mailu#2699]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version
Docker Engine 23.0.1
Docker Compose version v2.16.0
- Version: `master`

## Description

Mail system has only been running for a week however, inboxes are taking up 1.7Gb of space on indexes. Inbox doesn't contain actual mail, and has been deleted.

## Replication Steps
General use
it is powering the mail for a clients CRM system

## Observed behaviour
/var/lib/docker/volumes/<VOL_NAME>/_data/<INBOX>/xapian-indexes takes up a substantial amount of space. (1.7GB)

## Expected behaviour
disk usage of /var/lib/docker/volumes/<VOL_NAME>/_data/<INBOX> to be close to nothing after deleting all contents from the inbox

**Comment by nextgens** [comment]
See #2390 and https://github.com/Mailu/Mailu/issues/2390#issuecomment-1359565581 specifically.

This is the expected behaviour; indexes are only refreshed once every so many emails or after a specific amount of time has lapsed.

If disk-space usage is a concern, you can always turn the indexes off by adding an override to dovecot's config.
