### ISSUE TITLE
[maintenance] 'high availability' / multiple servers

### ISSUE THREAD

**Issue by elandorr** [Mailu/Mailu#2784]
I suppose most mailu installations are standalone docker stacks and not much care is given, since it's not 'that bad', if something is lost once every so often, for many small time ops. But I was wondering:

How would one properly run multiple servers that sync up?

As an example for why you might want to, even without HA in mind:

- Server A is on 1.9
- I set up a new 2.0 on another server B
- As per docs, I shut down A, sync one final time, then start B
- B now likely changes the internal databases, maybe even changes folder structures
- A week later I find there's a bug in the 2.0, and I want to go back

I can't just use the old env/compose file now.

Another case would be to comply with standards. Only having 1 MX is not compliant I was told.

Another case would be distributing load. You can set 2 MX records at the same priority, which should lead to 50:50 randomization.

But how would you sync the data? And how would you do so continuously?

Generic internet searches haven't really helped at all for finding out how major ops handle this.

Posts like [this one](https://serverfault.com/questions/303554/how-to-build-a-high-availability-postfix-system) suggest it's a giant PITA and not realistically doable without having a load of devs create a custom solution where everything is stored in network-capable databases. Like one poster there said, 'we don't seek to stroke our egos'. Unnecessary complexity is bad.

I'd still be curious. Also for another reason: How do commercial hosters handle the sheer size? Even with all the money in the world, a single server can't hold i.e. all of gmail. Is there a standard approach?

Thanks for all input!

**Comment by t0mtaylor** [comment]
I have it running docker swarm across 3 servers all sync'd with failover containers and a `handfull` of of scripts i've wrote myself to keep the swarm in check (it requires lots of monitoring and attention) - it can be done but its not for the faint hearted!

Good Luck!

**Comment by elandorr** [comment]
@t0mtaylor Very nice! I thought mailu abandoned the swarm thing a while ago?

If you feel like telling (no need to really, I'm just curious how the pros do it)

How do you sync? One big network share?

Beyond the mails, how do you handle mailu's own data? What about version mismatch?

**Comment by efernau** [comment]
This issue has been raised here a few times, but I don't think a complete solution is public.
For the most people, a backup MX is unnecessary because mail servers will not hard-bounce emails as long as the failed server is restored within three days. The servers will continue to attempt delivering messages once the server is operating again.

In my opinion, a solution for addressing the issue of multiple Servers, in case one of them is not reachable, or update, is to implement a High Availability setup. This can be achieved by available solutions for databases like Postgres and Mariadb. The mail folders could be synchronised with rsync.  Additionally, having multiple instances of front/nginx, smtp/postfix, and admin are also helpful.
However, version mismatch could lead to problems in this way.
