### ISSUE TITLE
fetchmail preserve timestamp

### ISSUE THREAD

**Issue by nmahadkar** [Mailu/Mailu#282]
anyway to get fetchmail to preserve timestamp?

**Comment by kaiyou** [comment]
What do you mean preserve timestamp? does it currently modify the mail timestamp?

**Comment by nmahadkar** [comment]
Correct. The date and time is changed to current when fetchmail imports the mail. The original delivery date and time are not preserved

**Comment by kaiyou** [comment]
I am not sure if this is possible at all, because the last received field is not added by Fetchmail but by Postfix itself, which could be interpreted as the mail delivery date by your client. Although I do not believe that Fetchmail changes the `Date` header, thus if your client displays that date and time, Fetchmail should be transparent.

**Comment by nmahadkar** [comment]
I have been researching this issue a bit. Maybe this can shed some light on the issue. 

https://superuser.com/questions/858534/fetchmail-to-keep-original-date-time

**Comment by kaiyou** [comment]
Nice article, thank you. Unfortunately the article is right: this cannot be properly accomplished if Fechmail delivers to an MTA, which it does in Mailu. What email client do you use, maybe it can be configured to display the `Date` field instead?

**Comment by nmahadkar** [comment]
My preference is to use webmail. Rainloop.  Maybe this should be approached from a different angle. The original reason for this feature is to simplify migration. Something that can be implemented from the admin panel and make it end user capable. Would love your thoughts.

**Comment by muhlemmer** [comment]
Should we close this?
