### ISSUE TITLE
Client setup shows 465 as default TSL submission port

### ISSUE THREAD

**Issue by cebor** [Mailu/Mailu#2820]
### Environment

- [X] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

The Client setup shows port 465 as default submission port for TSL, but this is wrong, on 465 only SSL works, TSL works only on port 587.

Also 465 was reassigned by IANA and 587 is the more common port this time.

Is there any reason why 465 is displayed instead of 587?

Maybe both ports should displayed: 465 (SSL), 587 (TSL)

## Replication Steps

Go to the admin and click "Client setup" in the menu side bar.

<img width="1526" alt="Screenshot 2023-05-14 at 06 04 25" src="https://github.com/Mailu/Mailu/assets/1576120/96d4375d-ee3c-4b58-8a6a-4d8ccb467dc0">

**Comment by nextgens** [comment]
I believe you are confused by the terminology here.

SSL is the old name of TLS: nowadays TLS is used on both ports, either implicitly (465) or explicitly (587).

There are numerous problems directly related to explicit TLS, as seen on https://www.usenix.org/conference/usenixsecurity21/presentation/poddebniak and the safer option is to use implicit TLS everywhere, that's why we nudge clients to be configured that way. It is likely that some future version of Mailu will drop support for explicit TLS altogether.

**Comment by nextgens** [comment]
Just to clarify: this isn't a lubie of mine: RFC 8314 is explicit about it. See https://datatracker.ietf.org/doc/html/rfc8314

**Comment by cebor** [comment]
Yes you right it's all about the versioning of the security layer. 

But if you try to connect via TSL to port 465 in a gmail account it does not work. Only accepts SSL on 465 and TSL on 587. Maybe it's because STARTTLS is only accepted on 587 if you look into the nginx config.

https://github.com/Mailu/Mailu/blob/master/core/nginx/conf/nginx.conf#L394
