### ISSUE TITLE
Postfix times out when I connect to it

### ISSUE THREAD

**Issue by dzervas** [Mailu/Mailu#2861]
### Environment

- [x ] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0.14`

## Description
The problem is that I can't receive e-mails.

## Replication Steps
So I've traced it:
- tried to connect to port 25 over the internet with telnet - works till `rcpt to` command (and after ~10-20s it responds with `451 4.3.2 Internal server error`
- same when I connect from host
- same when I connect within the container (port 25)

## Observed behaviour
E-mails do not get delivered
Logs from the smtpd container:
```

smtp_1       | Jun 20 23:40:26 e-restaurants postfix/smtpd[347]: connect from mailu_front_1.mailu_default[192.168.203.3]
smtp_1       | Jun 20 23:40:26 e-restaurants postfix/smtpd[347]: lost connection after CONNECT from mailu_front_1.mailu_default[192.168.203.3]
smtp_1       | Jun 20 23:40:26 e-restaurants postfix/smtpd[347]: disconnect from mailu_front_1.mailu_default[192.168.203.3] commands=0/0
```

## Expected behaviour
Not timeout and receive the email.

---

My domain is e-restaurants.gr and a valid inbox is `thisisabeautifultest`
Maybe something's wrong with my DNS records?

EDIT: `mailu.env` https://pastebin.com/UBxwkMqJ and `docker-compose.yml` https://pastebin.com/BhDM1D47
EDIT2: I also found these logs in the `front` container:

```

front_1      | 2023/06/20 23:48:06 [info] 24#24: *213 client <client ip>:53369 connected to 0.0.0.0:25
front_1      | 2023/06/20 23:48:08 [info] 23#23: *205 upstream timed out (110: Operation timed out) while connecting to upstream, client: 87.253.233.105 using starttls, server: 0.0.0.0:25
front_1      | 2023/06/20 23:48:08 [crit] 23#23: *205 SSL_shutdown() failed (SSL: error:0A000123:SSL routines::application data after close notify) while connecting to upstream, client: <client ip> using starttls, server: 0.0.0.0:25
```

**Comment by dzervas** [comment]
I also see:
```
smtp_1       | DEBUG:root:Received bytearray(b'domain e-restaurants.gr')
smtp_1       | DEBUG:root:Request domain/e-restaurants.gr
smtp_1       | DEBUG:root:Table get e-restaurants.gr
smtp_1       | DEBUG:root:Table get e-restaurants.gr is e-restaurants.gr
smtp_1       | DEBUG:root:Replying b'OK e-restaurants.gr'
smtp_1       | DEBUG:root:Received bytearray(b'transport e-restaurants.gr')
smtp_1       | DEBUG:root:Request transport/e-restaurants.gr
smtp_1       | DEBUG:root:Table get e-restaurants.gr
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
```

**Comment by ghostwheel42** [comment]
Please show what you send wend talking to mailu smtp port using telnet.
I think the line `eceived bytearray(b'transport e-restaurants.gr')` should contain a complete email address.

**Comment by dzervas** [comment]
```
ehlo mydomain.com
mail from: <asdf@mydomain.com>
rcpt to: <thisisabeautifultest@e-restaurants.gr>
data
Subject: test
hello
world
.
quit
```

**Comment by GSimonHU** [comment]
Hi,
had this issues since switching to 2.0 and log messages though my setup is in kubernetes, the fix was for me to change the master.cf file (/conf/master.cf) in postfix, not sure why but max process was set to 1 and postfix was slow/timing out when sending bulk emails

From:
# service type  private unpriv  chroot  wakeup  maxproc command + args
#               (yes)   (yes)   (yes)   (never) (100)

# Exposed SMTP service
smtp      inet  n       -       n       -       1       smtpd

# Internal SMTP service
10025     inet  n       -       n       -       1       smtpd


To:
# service type  private unpriv  chroot  wakeup  maxproc command + args
#               (yes)   (yes)   (yes)   (never) (100)

# Exposed SMTP service
smtp      inet  n       -       n       -       -       smtpd

# Internal SMTP service
10025     inet  n       -       n       -       -       smtpd

Cheers

**Comment by nextgens** [comment]
@dzervas did this actually fix the problem you were experiencing?

**Comment by dzervas** [comment]
@nextgens I can't test it at this moment, will report back soon

**Comment by ghostwheel42** [comment]
@dzervas does the command `docker compose exec admin flask mailu config-export domain` list the domain `e-restaurants.gr`?

**Comment by dzervas** [comment]
yes:
```
domain:
  - name: e-restaurants.gr
    dkim_key: <hidden>
```
