### ISSUE TITLE
would like to add another sites to to Mailu/Nginx configuration

### ISSUE THREAD

**Issue by alexsalex** [Mailu/Mailu#2864]
This is future request for mailu nginx container!
This is related to "front" container.

The point: I DONT WANT TO INSTALL 100500 nginx containers on one host! I would like to use front nginx container fow my ONLY ONE site on the same server where mailu installed.

Right now I use it like this:

Crate share from container to host: "-v /mailu/nginx:/etc/nginx"
Run container once to create the files
Make this share RO
Edit nginx.conf to add ONLY one line: "include /etc/nginx/conf.d/*.conf" in to HTTP section (NOT IN SERVER SECTION like the wrapper folder do)
Restart the container and enjoy
SO I WOULD LIKE TO DO NOT DO ALL THIS STEPS. Its not impact anything if Mailu team in the front container will allow the "server" configs.

**Comment by ghostwheel42** [comment]
Hi alexsalex,
you could create a PR for this. But the include line seems to be in the config already here: https://github.com/Mailu/Mailu/blob/ad2add2b60852da2803dd2c1f3934d7f8067fb70/core/nginx/conf/nginx.conf#L302
Alex

**Comment by Diman0** [comment]
This means you need to modify your docker-compose.yml so that a folder is host mounted to /etc/nginx/conf.d/; 
After that you can add your extra  nginx config to the host-mounted folder. You can use this to add your own server blocks.

This is undocumented by design. Mailu is not meant to be used as a reverse proxy for other websites. This `include` line is only added for the tinkerers. You can use it at your own risk.

We are not planning to add general support for this.

**Comment by ALFAMAS** [comment]
> This means you need to modify your docker-compose.yml so that a folder is host mounted to /etc/nginx/conf.d/; After that you can add your extra nginx config to the host-mounted folder. You can use this to add your own server blocks.
> 
> This is undocumented by design. Mailu is not meant to be used as a reverse proxy for other websites. This `include` line is only added for the tinkerers. You can use it at your own risk.
> 
> We are not planning to add general support for this.

can you explain how can I do that
