### ISSUE TITLE
Unable to login via client if your email address has a caps

### ISSUE THREAD

**Issue by Angedestenebres** [Mailu/Mailu#289]
As said in the title.

In my case, I got this issue with ThunderBird and my email address in my settings started by Ange (instead of ange).
After removing the caps, it worked just fine!

**Comment by kaiyou** [comment]
Indeed the query should not be case sensitive, many users reported issues with this.

**Comment by kaiyou** [comment]
After playing around for hours with custom comparators in SQLAlchemy, I feel stuck because the `email` field of email objects (User, Alias) is generated as a declared_attr and primary key at the same time. Thus, it can not be wrapped in a `column_property` for specifying the comparator, nor could I use a custom type with a specific column attribute.

The current fix will set a collation on the field, which will only be compatible with SQLAlchemy for now. We will have to improve this if we want to be compatible with PGSql and `citext` for instance.

**Comment by kaiyou** [comment]
This is fixed in `master`, could anyone give it a try?
