### ISSUE TITLE
front hangup on restart

### ISSUE THREAD

**Issue by gizocz** [Mailu/Mailu#341]
When front container restarts it logs only "Hangup" and does not start. How to reproduce: "docker-compose restart front" OR "systemctl restart docker" OR reboot the machine.

Problem is "nginx -s reload" in config.py. On the first run, it logs 'nginx: [error] open() "/var/run/nginx.pid" failed (2: No such file or directory)'. If the container restarts, the "/var/log/nginx.pid" exists, but the not the process, and "nginx -s reload" is the last command executed, "Hangup" is logged, and container exited with code 129.

**Comment by kaiyou** [comment]
Thanks for reporting, will fix urgently.

**Comment by MadOtis** [comment]
FWIW, it's still happening in v1.5.1 (not sure what version the fix on Feb 8 went into), but it just happened to me this afternoon.

As a work-around to get front running again (since it dies before I can get into the container and manually remove the pid file), I used this work-around:

1. Manually created a folder named 'pids' in the /mailu folder.
2. Manually added a mount to the front container in docker-compose.
3. docker-compose restart the stack.
