### ISSUE TITLE
Server becomes unresponsive when nginx logs non-UTF-8 character

### ISSUE THREAD

**Issue by hrittich** [Mailu/Mailu#3627]
## Environment & Version

- `docker compose version`: 2.29.1
- Version:

  ```
  ghcr.io/mailu/admin:2024.06
  ghcr.io/mailu/rspamd:2024.06
  clamav/clamav-debian:1.2.3-45
  ghcr.io/mailu/fetchmail:2024.06
  ghcr.io/mailu/nginx:2024.06
  ghcr.io/mailu/dovecot:2024.06
  ghcr.io/mailu/oletools:2024.06
  postgres:14
  redis:alpine
  ghcr.io/mailu/unbound:2024.06
  ghcr.io/mailu/postfix:2024.06
  ghcr.io/mailu/webmail:2024.06
  ```

## Description

During the last few weeks we have observed multiple times that the SMTP server as well as the webmailer of our Mailu installation was not responding to any requests. A closer inspection using `strace` showed that all nginx instances were hanging in a blocking write call. The destination of the write call was a pipe.

Inspecting the [start.py script](https://github.com/Mailu/Mailu/blob/aa52bbb731c374a707df41588a108cedaca71fc4/core/nginx/start.py) revealed that nginx is started using a function called `run_process_and_forward_output`, which is defined in a file called [socrate/system.py](https://github.com/Mailu/Mailu/blob/aa52bbb731c374a707df41588a108cedaca71fc4/core/base/libs/socrate/socrate/system.py). This method starts the (nginx) process by connecting its output to two pipes. Then, two threads are created, each of them reading from the one of the pipes. In the logs (see below), we found an error message stating that in one of the threads an exception was raised, due to an invalid character. This caused the corresponding thread to terminate, which implied that no data was being read from the pipe nginx stdout/stderr is writing to. The moment the pipe buffer was full, nginx blocks indefinitely trying to write to stdout/stderr.

Note that this is probably a critical bug, since if an attacker is able to provoke nginx to log a non-UTF-8 character, the entire server becomes unresponsive. This could be used for a denial of service attack.

## Replication Steps

We have no direct way of replicating the bug. The bug should be triggered by managing to cause nginx to log a non-UTF-8 character.

## Observed behaviour

Mailu becomes unresponsive.

## Expected behaviour

Mailu should handle non-UTF-8 characters gracefully.

## Logs

```
mailu_front  | Exception in thread Thread-2 (forward_text_lines):
mailu_front  | Traceback (most recent call last):
mailu_front  |   File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
mailu_front  |     self.run()  File "/usr/lib/python3.12/threading.py", line 1010, in run
mailu_front  |     self._target(*self._args, **self._kwargs)
mailu_front  |   File "/app/venv/lib/python3.12/site-packages/socrate/system.py", line 155, in forward_text_lines
mailu_front  |     current_line = src.readline()
mailu_front  |                    ^^^^^^^^^^^^^^
mailu_front  |   File "<frozen codecs>", line 322, in decode
mailu_front  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfa in position 164: invalid start byte
```

**Comment by koraa** [comment]
Our solution was to replace the entire script with supervisord.

I do not think the `run_process_and_forward_output` is even needed in the first place. If the subprocesses simply inherit the stdout/stderr file descriptors, they can directly write to them. No need to filter and open threads.

**Comment by nextgens** [comment]
Which Mailu version is that with? It's supposed to be fixed in 2024.06.23

What does `docker compose exec front cat /version say for both of you?

**Comment by hrittich** [comment]
> What does `docker compose exec front cat /version` say for both of you?

The output is `2024.06.16`. (For both of us, since we are both maintaining the same server.)

**Comment by nextgens** [comment]
Upgrade to current; reopen if you can still reproduce it please.

**Comment by nextgens** [comment]
Let me recap: you have submitted an issue for a bug **that we think has been fixed in a released version**.
You think that you understood it better than maintainers and have a "better" way to fix it, yet you have fallen short of sending a PR or actually testing whether you could actually reproduce it with the current version, yet you whine about it.

Until you can send me a test-case that enables reproduction of the issue you say still exists, I won't look into it again. Getting nginx to log non-utf8 is trivial: by default both Referrer and User-Agent are logged. You say that the current code still chokes on decoding: PoC||GTFO; the test case is likely a one-liner that we would gladly add to our tests.

For your information:
- We think that the root cause has been addressed. The part of the code that was decoding the output as an UTF8 string is gone: the file descriptors of the pipes are now open in binary mode; it shouldn't raise any exception related to a failure to decode any-more since it's not decoding any-more; see #3618 
- Guarding against readline throwing is something we could do... but then again, what would you do after you have caught a ValueError or an UnsupportedException? Log the problematic bytes? How much of it (since readline() is broken it has to be some arbitrary finite quantity)? Do you recover from it and if so, how?
- FYI previous versions of Mailu didn't have the wrapper; It was introduced to "fix postfix". I remain open-minded about it and would welcome a PR that does get rid of it if you can log filtering work on postfix without; same thing: PoC||GTFO

**Comment by ghostwheel42** [comment]
> Nothing of relevance to this issue has changed, it won't magically go away if we upgrade to the newest version; neither will shirking our responsibility as admins and deploying a known bug help to resolve this issue.

Hi. Thanks for reporting. This is the relevant change to fix the decoding error:

https://github.com/Mailu/Mailu/commit/4a49234afa2e762d178f46b3da8365164e3fb765#diff-447d7b758d739c31b312ca24feaa822abf5998c3ed0f6b4066b3cf1e47ff6cf7L172

Alex

**Comment by koraa** [comment]
Hi @nextgens, hi @ghostwheel42,

I gave the underlying Popen code a thorough review. What I found is, that it is surprisingly hard to use this API correctly.

I do think `forward_text_lines` still lacks error handling.

https://github.com/Mailu/Mailu/blob/aa52bbb731c374a707df41588a108cedaca71fc4/core/base/libs/socrate/socrate/system.py#L163C1-L166C32

Using Popen without `text=True` as was done in the [patch](https://github.com/Mailu/Mailu/commit/4a49234afa2e762d178f46b3da8365164e3fb765#diff-447d7b758d739c31b312ca24feaa822abf5998c3ed0f6b4066b3cf1e47ff6cf7L172) does help. Popen's init always uses `io.open(<file>, 'wb', <bufsize>)` and wraps the streams in `io.TextIOWrapper` when `text_mode=True`. So without the flag, it returns file descriptor based streams.
 
https://github.com/python/cpython/blob/3275cb19530fb5c7115cf8313f1ada9621ed3a92/Lib/subprocess.py#L1018C13-L1033C62

So the functions being used are really:

- _io_FileIO_read_impl in [Modules/_io/fileio.c, line L853](https://github.com/python/cpython/blob/3275cb19530fb5c7115cf8313f1ada9621ed3a92/Modules/_io/fileio.c#L853)
- _io_FileIO_write_impl in [Modules/_io/fileio.c, line L916](https://github.com/python/cpython/blob/3275cb19530fb5c7115cf8313f1ada9621ed3a92/Modules/_io/fileio.c#L916)
- _io__IOBase_readline_impl in [Modules/_io/iobase.c, line 560](https://github.com/python/cpython/blob/3275cb19530fb5c7115cf8313f1ada9621ed3a92/Modules/_io/iobase.c#L560)
- _Py_read [Python/fileutils.c, line 1859](https://github.com/python/cpython/blob/3275cb19530fb5c7115cf8313f1ada9621ed3a92/Python/fileutils.c#L1859)
- _Py_write [Python/fileutils.c, line 2029](https://github.com/python/cpython/blob/3275cb19530fb5c7115cf8313f1ada9621ed3a92/Python/fileutils.c#L2029)

One of the biggest potential sources of an exception would be the [EINTR](https://man7.org/linux/man-pages/man3/errno.3.html) system error – i.e. the error that is thrown when a unix signal is sent to a process while a system call is being executed. There is some code in the above functions handling this case; there is also a lot of other very very complicated error handling and a lot of NULL propagation in the above code and I would not trust it to never raise exceptions.

A relatively easy fix would be to add exception handling to `forward_text_lines` and deliberately crash the entire process on an error:

```python
import logging
import sys

def forward_text_lines(src, dst):
    try:
        while True:
            current_line = src.readline()
            dst.write(current_line)
    except Exception as e:
        logging.error(traceback.format_exc())
        sys.exit(1)
```

There is an even easier fix: Let the operating system handle forwarding of stdout & stderr. The [`subprocess.Popen`](https://docs.python.org/3/library/subprocess.html#frequently-used-arguments) documentation states:

> stdin, stdout and stderr specify the executed program’s standard input, standard output and standard error file handles, respectively. Valid values are None, PIPE, DEVNULL, an existing file descriptor (a positive integer), and an existing file object with a valid file descriptor. With the default settings of None, no redirection will occur.

We could rewrite `run_process_and_forward_output` with this knowledge to let the operating system handle stream forwarding like this:

```python
def run_process_and_forward_output(cmd):
    process = subprocess.Popen(cmd)
    return process.wait()
```

This – in essence – is the functionality of [`subprocess.run()`](https://docs.python.org/3/library/subprocess.html#subprocess.run), so the code simplifies to:

```python
def run_process_and_forward_output(cmd):
    return subprocess.run(cmd).returncode
```

This should solve the issue of exceptions caused by stream forwarding comprehensively.

There are a couple more issues in the `start.sh` code caused by the script running multiple processes:

- `./letsencrypt.py` OR `./certwatcher.py` OR nothing
- `dovecot -c /etc/dovecot/proxy.conf`
- `/usr/sbin/nginx -g 'daemon off;'`

On linux processes should be [`wait(2)`-ed](https://man7.org/linux/man-pages/man2/wait.2.html) upon, otherwise zombie processes may be created. I suppose dovecot will take care of this itself since it deamonizes after after startup, but the python scripts won't.

This script also allows for the possibility that dovecot crashes with the container and nginx staying alive; this could lead to a degraded system.

Personally, I would solve these problems by rewriting `start` to just set LD_PRELOAD to load the hardened malloc implementation, provision the configuration, create a [supervisord](http://supervisord.org/introduction.html) config to start all the subprocesses and finally [`execl`](https://docs.python.org/3/library/os.html#os.execl) into supervisord.

This would preserve the current functionality and outsource all the complex process management to [supervisord](http://supervisord.org/introduction.html].

https://github.com/Mailu/Mailu/blob/aa52bbb731c374a707df41588a108cedaca71fc4/core/nginx/start.py#L15C1-L18C42

**Comment by nextgens** [comment]
We all agree that error handling and sub-process management could be done better. Patches are welcome.

Capturing stdout/stderr is required for [LogFilter](https://github.com/Mailu/Mailu/blob/master/core/base/libs/socrate/socrate/system.py#L32) to work; all your suggestions so far but the one involving adding new belts and suspenders would break it. Bailing out with a return code and a stack-trace is only marginally better than what is currently done: we already get a stack-trace (since it's not caught).

**Comment by koraa** [comment]
Hi @nextgens,

> We all agree that error handling and sub-process management could be done better. Patches are welcome.
> 
> Capturing stdout/stderr is required for [LogFilter](https://github.com/Mailu/Mailu/blob/master/core/base/libs/socrate/socrate/system.py#L32) to work; all your suggestions so far but the one involving adding new belts and suspenders would break it. Bailing out with a return code and a stack-trace is only marginally better than what is currently done: we already get a stack-trace (since it's not caught).

As a professional engineer, I discuss architecture changes before applying them. Otherwise, there is a danger of running off in an entirely wrong direction or of spending much time on a patch that is not wanted in the first place.

The two biggest issues with `forward_text_lines` are::
                self.stream.buffer.write(line)
                self.stream.buffer.write(cr)
                self.stream.flush()
            self.buffer = rest

- The exception trace is hidden far down in the log file; its hard to find because the other processes keep sending output
- Nginx starts to hang because its output is no longer read

Thank you for explaining the LogFilter functionality; this one is hard to spot from just looking at the source code. I should point out that this introduces an additional source of exceptions in `forward_text_lines` from bugs in LogFilter.

Is there any actual interest in fixing these issues? Would there be interest in accepting a pull request that adds exception handling as I previously suggested? I am not sure, because your invitation to write a pull request says yes but the specific fix I proposed above is not acceptable. Is this correct?

**Comment by nextgens** [comment]
> As a professional engineer, I discuss architecture changes before applying them. Otherwise, there is a danger of running off in an entirely wrong direction or of spending much time on a patch that is not wanted in the first place.

So do we; Please read https://mailu.io/master/contributors/guidelines.html#what-behavior-is-tolerated

This issue is the wrong forum: the bug that was reported does not affect the current release.

Please open a new one describing the problem(s) or improvement(s) you would like to make. If you want explicit feedback, please tag it [RFC] or [join us on matrix](matrix:#mailu-dev:matrix.org) and we can take it from there.

[...]

> Is there any actual interest in fixing these issues? Would there be interest in accepting a pull request that adds exception handling as I previously suggested? I am not sure, because your invitation to write a pull request says yes but the specific fix I proposed above is not acceptable. Is this correct?

Yes to all of the above.
