### ISSUE TITLE
Email alias not delivering to external email addresses

### ISSUE THREAD

**Issue by spoulson** [Mailu/Mailu#384]
When configuring email aliases, I can create arbitrary addresses on my hosted mail domain and specify 1 or more target email addresses.

However, email is not actually going out to the external email addresses.  The aliases only work if the destination is local.

I'm having trouble locating MTA logs to see why this could be.  Unless I missed it, there's no mention in the documentation.

**Comment by kaiyou** [comment]
The emails should be routed properly, can you send emails out however?

You can display SMTP logs using:
```
docker-compose logs --tail=<nb of lines> -f smtp
```

**Comment by kaiyou** [comment]
Closing for now, feel free to re-open.

**Comment by Ztuff** [comment]
I am experiencing the same issue here, trying to catch-all and forwarding (by alias) to my Gmail inbox.

smtp log:
`smtp_1       | postfix/anvil[273]: statistics: max connection rate 1/60s for (10025:172.18.0.4) at Oct  4 17:51:41
smtp_1       | postfix/anvil[273]: statistics: max connection count 1 for (10025:172.18.0.4) at Oct  4 17:51:41
smtp_1       | postfix/anvil[273]: statistics: max cache size 2 at Oct  4 17:52:28
smtp_1       | postfix/smtpd[280]: connect from mailu_front_1.mailu_default[172.18.0.7]
smtp_1       | postfix/smtpd[280]: 0D6C47613AC: client=unknown[209.85.219.179]
smtp_1       | postfix/cleanup[284]: 0D6C47613AC: message-id=<CAD_ru7Giym37PNkpPy96MJnyVE9QZAq1E9jt1ozJu8NR7DdfOA@mail.gmail.com>
smtp_1       | postfix/qmgr[113]: 0D6C47613AC: from=<thisonedoesntwork@gmail.com>, size=2641, nrcpt=2 (queue active)
smtp_1       | postfix/lmtp[285]: 0D6C47613AC: to=<thisoneworks@mydomain.dk>, orig_to=<example@mydomain.dk>, relay=imap[172.18.0.11]:2525, delay=0.68, delays=0.61/0/0.01/0.07, dsn=2.0.0, status=sent (250 2.0.0 <thisoneworks@mydomain.dk> SHW2JxNYtlsABgAAX360ww Saved)
smtp_1       | postfix/smtpd[280]: disconnect from unknown[209.85.219.179] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
smtp_1       | postfix/smtp[286]: 0D6C47613AC: to=<thisonedoesntwork@gmail.com>, orig_to=<example@mydomain.dk>, relay=gmail-smtp-in.l.google.com[108.177.127.27]:25, delay=1.2, delays=0.61/0.01/0.41/0.21, dsn=2.0.0, status=sent (250 2.0.0 OK 1538676756 bz20-v6si1425076ejb.32 - gsmtp)
smtp_1       | postfix/qmgr[113]: 0D6C47613AC: removed`

I have set two destinations:
thisoneworks@mydomain.dk
thisonedoesntwork@gmail.com

As my made-up names imply, I receive the mail at my locally hosted mail, but nothing arrives in Gmail. Forwarding and POP3 import works fine for Gmail, with the exception that each individual mail address needs to be forwarded/imported separately, which is why I'm going for the alias approach in the first place.

**Comment by Ztuff** [comment]
Scratch that, I think that it may have been an issue that the test mail I sent was through the same Gmail address as the one I set as destination for the catch-all alias.

I just received an e-mail from a caught address, which I had just signed up for an unrelated service.
