### ISSUE TITLE
Fetchmail error

### ISSUE THREAD

**Issue by adi90x** [Mailu/Mailu#412]
Hello,
On a newly installation, fetchmail container fail because fetch table seems to be missing... 

Is it a known error ?

**Comment by kaiyou** [comment]
It is not, and the fetch table should be created by the admin container on first launch. Did you check the sqlite?

**Comment by adi90x** [comment]
Hello,
Yeah I guess it is link to the NFS share I am trying to use, seems that
sqlite3 doesn't like that at all and is doing random things !!

I will try to check whether I can move missing part to admin container or
maybe find a workaround !

**Comment by kaiyou** [comment]
I read locking is pretty bad on NFS indeed, so it might explain some erratic behaviors. I'll create a meta issue to keep track of what's missing to switch to other databases.

**Comment by adi90x** [comment]
Would be really nice to have a way to follow what's missing

**Comment by Aksem** [comment]
I have the same problem(tried both 1.5 and master):
`fetchmail_1  | sqlite3.OperationalError: no such table: fetch`

Also tried reinstall and restart, no effect.
Any ideas?

**Comment by kaiyou** [comment]
Aksem, does your Mailu instance run properly? Either there were issues when first initializing your database, or you do not have an initialized database yet.

**Comment by kaiyou** [comment]
Closing as outdated

**Comment by muhlemmer** [comment]
@ionutfilip

**Comment by muhlemmer** [comment]
Hi, this problem also appears in our testing suite on travis:
https://travis-ci.org/usrpro/Mailu/builds/437588016#L3927

However, we've created `usrpro:debugging` branch which combines our testing suite with `feat-abstract-db` and the test finishes successfully. Most probably because fetchmail no longer tries to access the [sqlite database directly.](https://github.com/Mailu/Mailu/commit/f9c6c98180fb34a1628871610babe89ab8094b4a#diff-9fa615993b76409e9c6b2a13396fcbaa):
https://travis-ci.org/usrpro/Mailu/builds/437645741

I think we can safely conclude that the "old" setup from master imposes a race condition on the sqlite database. The race is exposed on systems where I/O throughput is limited. (So NFS, vitrual machines like travis). In my humble opinion this issue should be considered open until we are able to merge `feat-abstract-database`.
