### ISSUE TITLE
mailu kubernetes setup / instructions

### ISSUE THREAD

**Issue by outbackdingo** [Mailu/Mailu#438]
ok docs must be missing something, or are not very clear i tried this with the yaml files and its resulted in
the below errors, can someone enlighten me.. ive got mailu running on rancher, so i attempted to migrate to kubernetes and not having alot of luck

mailu-admin
app: mailu-admin role: mail tier: backend
0 / 1
14 minutes
mailu/admin:stable
￼
more_vert
MountVolume.SetUp failed for volume "certs" : secrets "letsencrypt-certs-all" not found
error
mailu-imap
app: mailu-imap role: mail tier: backend
0 / 1
14 minutes
mailu/dovecot:stable
￼
more_vert
MountVolume.SetUp failed for volume "certs" : secrets "letsencrypt-certs-all" not found
check_circle
mailu-redis
app: mailu-redis role: mail tier: backend
1 / 1
14 minutes
redis:4.0-alpine
￼
more_vert
check_circle
mailu-security
app: mailu-security role: mail tier: backend
1 / 1
14 minutes
mailu/rspamd:stable
mailu/clamav:stable
￼
more_vert
error
mailu-smtp
app: mailu-smtp role: mail tier: backend
0 / 1
14 minutes
mailu/postfix:stable
￼
more_vert
MountVolume.SetUp failed for volume "certs" : secrets "letsencrypt-certs-all" not found
error
nginx-ingress-controller
k8s-app: nginx-ingress-controller
1 / 1
18 minutes
gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.11
￼
more_vert
Back-off restarting failed container

**Comment by romracer** [comment]
Hello!

The first line of the index.rst in the kubernetes docs folder currently indicates this is not well supported and has not been updated to use the nginx auth proxy.  I believe to use that deployment example, you'll need to use version 1.4 of Mailu or some older tags.

Good news though!  I also use Rancher and have recently begun migrating to Kubernetes.  This weekend I was able to successfully deploy Mailu to Kubernetes and migrate the data from my Rancher deployment.  I will provide updated deployment docs and an example soon (you'll also need the fix for #436).

In the meantime, I would point out that you'll need at least 3 Deployments because the "front", "webmail" and "admin" services all use port 80 and thus can not live in the same pod.

**Comment by outbackdingo** [comment]
great good to hear we are finally getting it back up to speed, question which kubernetes did you deploy ?
ranchers kubernetes, or DC/OS integrated kubernetes ?? or another basically i can start from scratch i have enough capacity to run 4 24gb nodes k8s nodes, and im only running mailu, a few nginx based web sites, and an ecommerce app on it

**Comment by outbackdingo** [comment]
i think my issue is specifically here ... not so familiar with kubernetes, MountVolume.SetUp failed for volume "certs" : secrets "letsencrypt-certs-all" not found

**Comment by ticruz38** [comment]
you need to deploy smth like kube-lego to generate the secret for you

**Comment by hacor** [comment]
@outbackdingo: @ticruz38 is right, you need a cert manager to create the certs for you.

I'm also trying to implement the newer version of Mailu onto Kubernetes, but it doesn't seem to work completely. I'm curious for @romracer to finish the documentation. I created a [Gist](https://gist.github.com/hacor/7f3f42255711961dc49d09ffdc0ddcba) with my current files. There's also a readme included.
I know it's not adviced to use the `latest` version of the containers, but as @romracer stated you need to use the `HOST_` variables to make sure to point to the right pods.

**Comment by hacor** [comment]
I created a pull request with some new manifests #544 
I tried to remove all the errors that were in my Gist provided earlier. All feedback is Welcome!

**Comment by kaiyou** [comment]
I just merged your pull request, thank you so much :)
