### ISSUE TITLE
DKIM documentation?

### ISSUE THREAD

**Issue by Harti** [Mailu/Mailu#500]
Thanks for creating Mailu!

Is there any setup documentation on how to enable DKIM with Mailu? [I was unable to find anything of use on the official documentation](https://mailu.io/search.html?q=dkim&check_keywords=yes&area=default); in fact, some of those pages linked me to README.md on this GitHub repo.

My emails are being marked as spam and I believe it's because the DKIM record is missing. In order to fix that, I would have to enter a public key on my domain's DNS records - but how would I make Mailu use the corresponding private key?

**Comment by mmoo9154** [comment]
@Harti, I had exactly the same issue.  After hunting around, here's what you need to do.  I'm assuming you have access to the admin page (e.g. https://example.com/admin).

On the main page, click on "Mail domains" at the bottom of the left hand column.

Then, click on the "Details" icon that is the left-most icon beside your mail domain.  (If you haven't created a mail domain yet, click on the "New Domain" button in the top right and create your new site.

Once you are on the Domain details page,..  It should be mostly blank.

Click on the "Regenerate keys" button at the top-right of the page, then click the "Confirm" button.

You will now see a list of 5 entries starting with *DNS MX entry* down to *DNS DMARC entry*, and you can come back to the details page if you ever need to see the keys.

There are four DNS records you should create: MX, SPF, DKIM, and DMARC.  The entries are pretty self-explanatory, but if you are not clear, add a comment and I'll spell out what you need to do for GoDaddy (that's who I use).

One of the things that's cool, but not obvious is that "Regenerate keys" stuffs the private key into the smtp container, so there is nothing you need to do to configure the smtp server.  It just starts adding dkim headers to outgoing email.  You can verify by checking the mail headers of any email you send out.

If this doesn't work for you, please add comments.

**Comment by Harti** [comment]
@mmoo9154 Thank you so much for posting your solution! However, I don't currently have access to the Admin panel (the issue being, I'm using a reverse-proxy and cannot get it to work - the front/webmail/admin architecture is not very transparent, I can get `webmail` to work, and do *the exact same thing* for `admin` but simply cannot access it ☹️ @kaiyou ).

Do you think there is another way without accessing that panel?

**Comment by hoellen** [comment]
What reverse-proxy are you using? If it is nginx, maybe I can help you. It works quite well for me.

**Comment by Harti** [comment]
I'm using https://github.com/SteveLTN/https-portal. 

I've set up the `webmail` container as `VIRTUAL_HOST=webmail.example.com`. When I visit that domain, it displays Rainloop. It is interesting to me that it ignores the `/webmail` in Mailu's `.env` file (i.e. I open the browser at `https://webmail.example.com/` and it works, `https://webmail.example.com/webmail` gives a 404, but that's ok for me as it is less verbose anyway).

I tried setting up the `admin` container as `VIRTUAL_HOST=webmail-admin.example.com` first, later I did the same for the `front` container (which I believe is responsible for serving both webmail and admin). But it doesn't work, regardless of if I append `/admin` or not. I tried checking the nginx/apache configs inside those containers, but I was unable to find the issue.

**Comment by mmoo9154** [comment]
**`front`** handles all of the incoming requests.  It redirects all http requests to be https, then it routes the incoming https requests to the various internal containers.  **`webmail`** is the container (virtual server) that handles all of the pages you are seeing.  The **`admin`** container handles all of the mailu admin.

If you haven't already, you should definitely `docker-compose logs -f --tail=20` to see your logs while you are trying to connect to https://example.com/admin and see if you get any log entries from **`front`** or **`admin`**.  I suspect you're not even getting the requests.

**Comment by hoellen** [comment]
As @mmoo9154  mentioned, it ignores the `/webmail` part  from the `.env` file because your reverse proxy is speaking with the `webmail` container instead of the `front` container. 
So you have to create a `location` in the config of your reverse proxy which e.g. pass admin and webmail requests to the `front` container with the right subpath from your `.env` file.

**Comment by Harti** [comment]
@mmoo9154 I have checked the logs, but they're not very helpful.


The proxy is set up as follows: 
```
DOMAINS: 'www.example.com -> http://web_container:80, 
webmail.example.com -> http://mailu_webmail_1:80, 
webmail-admin.example.com -> http://mailu_admin_1:80'
```

`www` and `webmail` work, `webmail-admin` doesn't.

mailu_webmail_1:
```
webmail_1    | 172.21.x.x - - [27/Jun/2018:08:16:57 +0000] "GET / HTTP/1.0" 200 1154 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
webmail_1    | 172.21.x.x - - [27/Jun/2018:08:16:58 +0000] "GET / HTTP/1.0" 200 1154 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
```

mailu_admin_1:
```
admin_1      | 212.77.x.x - - [27/Jun/2018:08:18:40 +0000] "GET / HTTP/1.0" 404 233 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
```

Notably, the IP is different. In the case of webmail, the IP being proxied is the docker host IP itself, but for admin, it's the client IP.
Since I'm doing the exact same thing for all three of those domains (and more than those three, too), and only admin acting up, I don't know where to find the issue in the admin container.

**Comment by Harti** [comment]
@kaiyou I'm sorry. I'm lost. I give up.

I did it like you said and I'm getting too many redirects (logs show 20 consecutive 301 errors) on /webmail and /admin. I don't understand any of this, can't fix this, can't describe nor guess what could be wrong. 

I guess I shouldn't have expected this to work with reverse proxies and installed something else.

**Comment by kaiyou** [comment]
It really works fine with a reverse proxy, one simply needs to proxy to the front container. I would really like that we solve the issue and identify what requires better documentation for other users to benefit from this.

Could you post some detailed configuration? (Leaving alone password and keys obviously)

**Comment by mmoo9154** [comment]
@Harti, I hope you stick with this a little more.

From your 6/27 post, I'm a little confused...  It looks like you might have a stand-alone proxy server standing in front of mailu_front_1.  If so, it's probably redundant, and it's definitely not be reaching inside the mailu_default bridge network to try and send http requests directly to mailu_webmail_1 or mailu_admin_1.


The whole point of mailu_front_1 is to isolate the internal containers so that all traffic has to pass through mailu_front_1 for validation.

mailu_front_1 is intended to be hardened enough to be connected to the raw, wild internet.

I'm also a little surprised that your mailu_webmail_1 resolves to 172.21.x.x while mailu_admin_1 resolves to 212.77.x.x.  The 172.21.x.x addresses look very much like what I would expect on the mailu_default bridge network.  You might want to try `docker network inspect mailu_default` and see what you get on your system.

But, the **212.77.x.x** address looks like an external IP address.  For instance, on my system, mailu_front_1 is on 172.18.0.7, mailu_webmail_1 is on 172.18.0.4, and mailu_admin_1 is on 172.18.08.

I'm a little surprised to find I can directly connect to http://172.18.0.4 from my Docker host's command line.  If you type `curl -Is http://172.21.x.x` (where 172.21.x.x is whatever the IP address of mailu_webmail_1 on the mailu_default network), you should see a 200 OK response on the first line.

If you type `curl -Is http://<ip-of-your-mailu_admin_1>` you should get a 404 NOT FOUND error, but if you `curl -Is http://<ip-of-your-mailu_admin_1>/ui/login` you will get a 200 OK response.

So, it looks like you **could** have your existing proxy server map:

```webmail.example.com -> http://mailu_webmail_1:80
webmail-admin.example.com -> http://mailu_admin_1:80/ui
webmail-admin.example.com/ui -> http://mailu_admin_1:80/ui
webmail-admin.example.com/static -> http://mailu_admin_1:80/static```

But, I would recommend the following mapping:

```webmail.example.com -> mailu_front_1:80/webmail
webmail-admin.example.com -> mailu_front_1:80/admin/ui```

**Comment by Harti** [comment]
After a little more fiddling around, I've got a...

# Working configuration:

`mail.example.com -> http://mailu_webmail_1:80`
`webmail-admin.example.com -> http://mailu_admin_1:80` 
(exposed 80 on each of those)

`https://mail.example.com` -> Rainloop (note there is no `/webmail` suffix required)
`https://webmail-admin.example.com/ui` -> Admin interface (`/` threw 404 errors, as mentioned before, so I threw a guess into the blue and appended `/admin` (404) and `/ui` (200))

**Comment by mmoo9154** [comment]
So... You are up and running?

**Comment by Harti** [comment]
Essentially, yes. The trick was appending `/ui` for the admin container.
