### ISSUE TITLE
What is this redis used for?

### ISSUE THREAD

**Issue by christhomas** [Mailu/Mailu#515]
https://github.com/Mailu/Mailu/blob/75a1bf967c9b34224642326b65f098002fc16331/docs/kubernetes/kubernetes-mailu.yaml#L25

Here is specified a Redis, but it is not used anywhere

**Comment by kaiyou** [comment]
It is used by the admin container for rate limiting and by dovecot for updating quotas.

It is possible that the dovecot usage disappear in favor of api calls to the admin container for reading and writing dictionaries. Otherwise it will very probably remain for the admin container and even host api caches in the future.
