### ISSUE TITLE
Support for external letsencrypt instance

### ISSUE THREAD

**Issue by darkblinded** [Mailu/Mailu#516]
I'm using mailu with rancher. While it's nice, that mailu includes letsencrypt, this does not work for me. I am hosting many services on many domains on this rancher instance, so I need to be able to do SSL handling, at least for HTTPS traffic, in my root loadbalancer to be able to route to the right container. For this I am currently using [janeczku/rancher-letsencrypt](https://github.com/janeczku/rancher-letsencrypt).  But there are two problems here:

* [janeczku/rancher-letsencrypt](https://github.com/janeczku/rancher-letsencrypt) generates a `fullchain.pem` and `privkey.pem` instead of `cert.pem` and `key.pem`
* mailu needs to be restarted manually when a new certificate is generated (at least I had this problem in `1.4`)

Is there any way, that I can run mailu with an external letsencrypt instance without having to do all of this manually?

Ideally I'm looking for a solution that also won't require editing config files after deployment to be able to create a template for mailu instances.

**Comment by kaiyou** [comment]
Regarding the file names, you could simply set some symlinks in your ``certs`` directories, that will seamlessly point to your ``fullchain.pem`` and ``privkey.pem`` when they change.

Also, instead of restarting, you could set the letsencrypt script to send a SIGHUP to the front container so it restarts without manual action.
