### ISSUE TITLE
Add possibility to remove header postfix or possibility to mount /etc/postfix

### ISSUE THREAD

**Issue by v1ru535** [Mailu/Mailu#532]
Hi,

Would it be possible to add a mount point for /etc/postfix or the possibility to modify/add configuration files to Postfix?
The goal being to remove sensitive Header Information to Postfix.

An example below:
_Set a new file:_
`/etc/postfix/header_checks`

_Contain:_
`/^Received:/ IGNORE`
`/^User-Agent:/ IGNORE`
`/^X-Sender:/ IGNORE`

_Add line in main.cf:_
`header_checks = regexp:/etc/postfix/header_checks`

Thanks in advance.

**Comment by hoellen** [comment]
You can customize your postfix configuration by providing an override file. There should be an directory in the root of mailu, called `overrides`. In this you can create a file `postfix.cf` and override your postfix configuration. 
But i think you don't need this, because the sensitive headers are [already removed](https://github.com/Mailu/Mailu/blob/master/core/postfix/conf/outclean_header_filter.cf).
Hope this helps you

**Comment by v1ru535** [comment]
Thanks @hoellen I will test this one.
I'll make a comeback here after test it.

**Comment by v1ru535** [comment]
Hi,

Thx for the tip @hoellen, `postfix.cf` in `overrides` works fine for extra conf.
I've set a relay for my instance, extra conf set in this file and it work like a charm.
