### ISSUE TITLE
Document how to connect other services to user Mailu user database

### ISSUE THREAD

**Issue by liquidat** [Mailu/Mailu#575]
The current documentation does not show how users are managed inside Mailu. However, this information is crucial if Mailu is supposed to work together with other applications. For example, I would love to connect  apps like Gitea and Nextcloud to Mailu, so that users of Mailu can login to Nextcloud as well.

**Comment by rakshith-ravi** [comment]
What's wrong with using SMTP authentication for Gitea and IMAP authentication for Nextcloud, and similar authentication methods for other services?

**Comment by liquidat** [comment]
@rakshith-ravi Nothing is wrong with that - those are very valid options!
Howeverm not all tools might support those, Gitea and Nextcloud were just examples. So I do wonder how the user database in Mailu works, and if it makes sense to connect to it or sync it to other databases. I would be happy to provide a documentation PR if someone sheds some light on how the user db works.

**Comment by rakshith-ravi** [comment]
Simple. Look into the main.db file that gets generated. It's an sqlite file that has the hash of the password based on the hashing algorithm selected in the .env file

**Comment by benyanke** [comment]
I'm following this one.

Also just linking to #420, #83, and #302, which are related.

**Comment by muhlemmer** [comment]
Best would be to use some kind of SMTP or IMAP plugin. The structure of the database does change from time to time, which is managed by migration scripts on the Mailu side. If you'd develop directly against the DB, you will need to keep track of these changes on your side.

The other way around might also be an option, since PR #612  is implemented it should become more  easy to connect Mailu to an alternative database.
