### ISSUE TITLE
Slow to Start / Unclear Logging

### ISSUE THREAD

**Issue by benyanke** [Mailu/Mailu#588]
When `/start.py` runs in the front container, the logs are held back until the python script finishes.

I'd like to propose two things, to make it easier to understand what is going on:

1) Consider disable python output buffering, so you can see the progress of the long-running commands (DH key gen)
2) More simply - add logging.

**Comment by muhlemmer** [comment]
Since PR #339, DHparam is included by default and does not need to be generated. This is valid for master. Now, after a `docker-compose up -d`, the services are up within a few seconds*. Do we still consider it useful to enable logging?

*ClamAV needs more time to download virus definitions the first time, but freshclam is quite verbose.

**Comment by benyanke** [comment]
I'd think that if it's up in under 30s, there's no need for more.
