### ISSUE TITLE
Splitting the repository and renaming the project

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#63]
Some changes are ongoing regarding the overall architecture and it feels necessary to expose some ideas and see if anyone has a better solution.

From the latest discussions, it has arised that:
- the monolythic admin interface is hard to maintain and audit;
- we need a way to launch tasks, both on-demand and scheduled;
- we need a place to centralize critical concerns like managing Docker operations.

From what I gather, what seem like a best long-term option is:
- a Web-based REST API in the admin container, no UI or anything fancy, maybe a CLI;
- a Celery worker with all Docker-related tasks in a separate container, handling certificates, restarts, updates, etc. ;
- a static admin interface served by the frontend or a third container, talking to the REST API;
- a Redis broker for tasks;
- the same SQLite database for data.

Only remaining question is: how should we share the model between the admin (REST) application and the Celery worker?

**Comment by kaiyou** [comment]
I feel stupid after saying it out loud. The Celery worker does not need to share the model or to access the database. It simply needs a token and could then query the API. Still not sure about the best way to go.

**Comment by curry684** [comment]
Let's continue the discussion from https://github.com/kaiyou/freeposte.io/issues/80#issuecomment-254078502 and https://github.com/kaiyou/freeposte.io/issues/64#issuecomment-254077525 here.

Splitting
---
I understand your point, for development and ease of mass deployment a monolithic repository is usually easier to maintain. One does not have to exclude the other though: [the Symfony framework](https://github.com/symfony/symfony) is a notable example of a monolithic repository that [maintains](https://github.com/symfony/security) [realtime](https://github.com/symfony/yaml) [read-only](https://github.com/symfony/dependency-injection) [splits](https://github.com/symfony/filesystem) of each of its 30-something separate components. Main reason is that this allows users to easily use either the full stack, or include the separate packages as they see fit. The Symfony founder has even [released the core of the tool](https://github.com/splitsh/lite) they do this with. 

Big advantage for this project would be to have easy [automated builds](https://docs.docker.com/docker-hub/builds/) that are always up to date and do not rely on locally building everything.

Naming
---
Like I said I feel the momentum of this project could be strong enough to warrant its own strong brand name. I took the liberty of reserving [Dockerpost](https://github.com/dockerpost/) for this purpose.

As I'm pretty much useless with Python and it's been 10 years since I installed a mailserver from scratch I'm not much help with development of the project, I'll happily help with the Docker and Git parts though, despite being short on free time currently.

**Comment by kaiyou** [comment]
Before I close the other issues, quick reminder of the original issues that lead here:
- how should we bundle optional features that are unlikely to be used by most users (eg. DNS server)
- how should we handle standard features (reverse proxy) that should be easily replaceable or disabled by power users

## Splitting

First, yes, centralizing issues and PRs is the main idea that lead to a single repository. Having separate read-only splits is a nice-to-have, I will have a look at their tool, I believe a Travis task could be setup to perform these at no cost.

However, automated builds are already setup and up to date for all images and published to the Docker Hub, with ``latest`` for the ``master`` branch and per-branch tags. Splitting is not a requirement for this.

In the end, if we publish read-only splits for people who would only like to clone a tiny bit of the project, having a separate organization starts making sense.

## Naming

If I may, I do not like "Dockerpost" for a simple reason: it's tied to the idea of using Docker, which is a nice tool but still a tool and not the purpose of the project itself. Also, "poste" was a personal reference to the french "Poste" which delivers mail in France. Still, I am open to changing the name if we agree on a great one.

Anyway, your help is welcome and you have already accomplished a lot with your advice. Thanks.

**Comment by kaiyou** [comment]
On the naming part, here are some additional suggestions gathered from friends:
- "Mailu", named after a small island in the Pacific,
- "Ismail", as in Abraham's son,
- "Mayl", don't like it, but still,
- "Koorier", awful, but still,
- "wiremail"
- "Dockerpost"

**Comment by curry684** [comment]
> If I may, I do not like "Dockerpost" for a simple reason: it's tied to the idea of using Docker, which is a nice tool but still a tool and not the purpose of the project itself.

It's clear and recognizable though, especially from a SEO perspective - I know I myself Googled half the world for "docker mail server". Secondly the project right now *is* tied to the idea of using Docker, hence the dockerfiles, the `docker-compose.yml` and all the base images from Docker Hub. If Rkt becomes a viable alternative one day and replaces Docker as the leading containerization platform it would need a project fork and a lot of work anyway to be able to launch RocketPost. And I've also taken the liberty to register the .com and .org domains before some smartass reading this topic does hehe.

I'm open to anything though, like I said I'm not in a position to take a leading role in the project, I'll just be more than happy to help with the Docker end of things as I do have knowledge and experience there and we'll likely base our company email infrastructure on it for the next few years.

For the other names - Koorier is way too confusing with another certain popular email project, and both that and Mayl are inconvenient from the perspective of being able to discuss a product at the coffee machine, consider telling a friend verbally "You should get Mayl or Koorier to replace your current mail server". Doesn't work  😄

**Comment by kaiyou** [comment]
I personally like "Mailu". The name is simple, not used anywhere noticeable, and not tied to a technology.

I understand your argument about Freeposte being tied to Docker anyway, yet I would not like the name to reflect the technology but the purpose and the philosophy instead (thus *free* and *poste*). Naming the project after an island that's probably been inhabited for longer than most industrial contries and has its own language sounds just fine. Otherwise, my favourite is still Freeposte despite the misconceptions about *free* software.

**Comment by kaiyou** [comment]
After a dozen discussions with friends, most seem to agree that "Mailu" (pronounced either "Mail you" or "Mah Ih Lu" whether or not you know about that small island) sounds nice and would be fairly SEO-friendly given that the island itself does is not very popular and that I reserved ``mailu.io``.

Also, I like the slogan "Insular email server".

**Comment by curry684** [comment]
Cheers, I'll try to get some scripting set up for that   :)

**Comment by kaiyou** [comment]
Closing this and moving to a separate issue for the original topic.
