### ISSUE TITLE
Mailu 1.5: Security vulnerability in SQLite

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#748]
Security vulnerability was reported here: https://blade.tencent.com/magellan/index_en.html

It is unclear if Mailu is affected, given no details are provided regarding the actual bug or exploit code. However, our images should be rebuilt as soon as package updates are available for Alpine and Debian.

## Update 29-01-2019

- `mailu:master` was updated around 02-01-2019;
- `mailu:1.5` was updated around 28-01-2019;

User that are running snapshots of those branches are advised to pull the latest images:
```
docker-compose pull
docker-compose up -d
```
- `mailu:1.6` uses SQLite 3.25.3 since release and was therefore not affected by this.

This issue will remain open as announcement and will be closed on month from now. -- @muhlemmer

**Comment by hoellen** [comment]
Alpine 3.8 updated to `sqlite 3.25.3` which fixes the vulnerabilities. We should trigger a rebuild, especially for 1.5.

**Comment by muhlemmer** [comment]
@hoellen: That would be problematic. `1.5` is pre-db abstraction through admin. This means that Dovecot and Postfix access the DB directly.
- Dovecot in `alpine:3.8` is buggy: #751 and #701. I don't want to push those bugs to users that are running an otherwise stable environment (and later also back-porting any fix)
- Postfix would be upgraded from `3.2.4` to `3.3.3`, which will break its database configuration we use. See #548.

Unless alpine will back-port the security update to `3.7`, the best would be to push for `1.6` release instead...

For `master` daily rebuilds are already configured after a talk regarding this on Matrix. Also we already merge some PR's today, so the rebuilt images should already be available to our users.

**Comment by hoellen** [comment]
@muhlemmer the `sqlite` update was also done on the `alpine 3.7` version

**Comment by muhlemmer** [comment]
I've triggered the rebuild. But let me tell you something funny. When I wanted to check the sqlite version in the containers, I realized we don't install the package at all, anywhere. Instead we depend on the library inside Python. Which to my conclusion is (on master):

```
[tim@docs demo]$ docker-compose exec webmail python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> print(sqlite3.sqlite_version)
3.16.2
```
Oops

`alpine:edge` also haven't had any python (re)build since August...

**Comment by hoellen** [comment]
Oh I'm sorry. I just checked the package version on the alpine website.

**Comment by muhlemmer** [comment]
Don't worry about it I made the same assumption. I think the Alpine build system is not recursively rebuilding dependent packages automatically after an update. Or the library came bundled with Cpython and need updating from their side. I will see if I can talk to Alpine devs tomorrow.

**Comment by muhlemmer** [comment]
So, some more investigations. Python3 depends on sqlite-libs, which reflects the currents SQLite package version. (alpine sub-package).

Alpine edge:
```
>>> sqlite3.sqlite_version
'3.26.0'
```
Alpine 3.8:
```
>>> sqlite3.sqlite_version
'3.25.3'
```
Alpine 3.7:
```
>>> sqlite3.sqlite_version
'3.21.0'
```
So on `Mailu:master` we are OK. `1.5` is still exposed.

It seems Alpine has patched SQLite for 3.7, 6 days ago:
https://git.alpinelinux.org/aports/commit/main/sqlite?h=3.7-stable&id=63ebe94564a865e66f3ee37fa683ce8edd3d19c6

However, the sqlite package has not yet been build and is still at version 3.21
https://pkgs.alpinelinux.org/package/v3.7/main/x86_64/sqlite

**Comment by muhlemmer** [comment]
This issue will be removed from the `1.6` milestone, as it is fixed in master. It will remain open for now on 1.5.

**Comment by muhlemmer** [comment]
Edited original post from @kaiyou. Triggering CC notification by this message.

**Comment by hoellen** [comment]
@muhlemmer So finally the sqlite package was updated to 3.25.3 yesterday. So I think after a rebuild we can close this issue.

**Comment by muhlemmer** [comment]
Rebuild is done and I've updated to top post. I'd prefer to keep this open for a while, so that users are still informed properly.
