### ISSUE TITLE
Expose log files to the docker host

### ISSUE THREAD

**Issue by senilio** [Mailu/Mailu#85]
Being able to access log files directly on the docker host would make for easily searchable logs which could be used for fail2ban, splunk/ELK analysis etc.

freeposte/logs/{http,imap,smtp,milter,webmail,antivirus}/<logfiles>

Just need to make sure logs are rotated for each component.

**Comment by kaiyou** [comment]
I agree about Fail2ban and am still thinking about the proper solution on the matter. 

However, Docker is very good at handling its logs and I believe most Freeposte containers output their logs to Docker. Instead of creating another structure for storing logs, you can use standard Docker tools.

For instance, have a look at Docker log drivers like Gelf to forward logs to Splunk or ELK, or access and parse logs using ``docker logs`` or the JSON files in ``/var/log/docker``.

**Comment by curry684** [comment]
There [are already dedicated tools for extracting Docker logs](https://github.com/gliderlabs/logspout), including a [Logstash adapter](https://github.com/looplab/logspout-logstash) to facilitate the ELK analysis. This part of the question is definitely out of scope for Mailu.

I do think a few of the more generic logfiles, specifically those related to mail flow, could be in shared volumes instead of only in Docker logs. I know I for one still prefer `grep` over Kibana for debugging why a mail wasn't received by someone.

**Comment by kaiyou** [comment]
The logstash logspout adapter is pretty much deprecated by the gelf log driver. Anyway, closing this since the question is answered.
