### ISSUE TITLE
Regular backup procedure?

### ISSUE THREAD

**Issue by andresmrm** [Mailu/Mailu#870]
What's the regular backup procedure for Mailu? Didn't find anything about it in the docs...
Just copping the `/mailu` folder? Will the DBs be correctly copied this way, or may they get corrupted?
Shutting down Mailu before copping the files to stop the DBs doesn't seem a good option...

**Comment by muhlemmer** [comment]
SQlite depends of file locking, so does Dovecot in managing the mailbox. So during write any files will be locked and any other program that wants to read will get blocked until available. You don't actually notice the block, because most writes are atomic. Also, there is nothing "actively" being written to the database. Only when creating/modifying domain, user, alias etc from Admin interface.

So yeah, its safe to copy/rsync the whole `/mailu` directory off-site while Mailu is running.

**Comment by andresmrm** [comment]
Thanks!

**Comment by gexterio** [comment]
Hi guys. I know that it's an anctient conversation but i have an issue and hope you can help me. I trying to copy whole /mailu folder but when run mailu with copied folder i loose all mails. With users and others all ok. Problem with only mails. What can be wrong? I'm using default DB (SQLite)
