### ISSUE TITLE
MX, SPF and DMARC - wrong domain? + suggestion

### ISSUE THREAD

**Issue by cr1st1p** [Mailu/Mailu#899]
I manage 2 domains (hostnames=domain1.com,domain2.com)
When viewing the details for 2nd domain, I get MX, SPF and DMARC entries referencing the 1st domain.
Unless there is a strong reason why, I consider this wrong. I double checked documentation (wikipedia) on these and I couldn't yet find a good reason for not using the appropriate domain.

Also, suggestion regarding dmarc:
You are using 'root@domain.com' in it, but I think it would be better to use something 
like 'dmarcreports@domain.com' and user should add himself an alias from dmarcreports to whatever he wants. Nicer, greater flexibility.
As a presentation form, maybe write both variants and tell about the alias.

**Comment by cr1st1p** [comment]
After a discussion, I think that due to *reverse* DNS setup, it might be indeed better to use the same hostname. Probably a notice somewhere to say that the first domain in the HOSTNAMES variable will be used in various locations even for the other domains would be helpful - so that people could put first the more 'nicer' domain.

Feel free to close.

**Comment by kaiyou** [comment]
Definitely okay with adding a notice in the docs. I'll close then.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

p.s. the configuration reference in the [documentation](https://mailu.io/master/configuration.html#common-configuration) does mention the first hostname is used for smtp,imap etc. The setup utility also mentions this.
