### ISSUE TITLE
sqlite storage

### ISSUE THREAD

**Issue by extremeshok** [Mailu/Mailu#94]
Just to confirm is postfix and dovecot using sqlite for user account alias mappings, etc.

**Comment by kaiyou** [comment]
Yes, every configuration item is stored in SQLite. The choice was motivated by the simplicity of SQLite and no strong requirements regarding performances.

The only configuration item that is not stored in SQLite are the DKIM keys, mostly because Rmilter does not support loading them from SQLite to the best of our knowledge.

**Comment by extremeshok** [comment]
wanted to confirm before i code some HA / multi-master stuff.

**Comment by kaiyou** [comment]
Well, the current design is hardly compatible with any multi-master architecture, unless you share the entire filesystem layer.

**Comment by extremeshok** [comment]
Actually its pretty easy to multimaster / HA without sharing the FS layer.


__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by kaiyou** [comment]
Could you develop?
